### ISSUE TITLE
Atom 1.0 Standalone Entry Items are not supported correctly

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#132]
<pre>=== This issue was migrated from JIRA ===
Type: Bug
Priority: Major
Status: Open
Resolution: UNRESOLVED
Reported by: justink
Assigned to: ROME Jira Lead
Created: Tue Jun 30 09:13:56 CEST 2009
Updated: Tue Jun 30 09:13:56 CEST 2009
Resolved: Tue Jun 30 09:13:56 CEST 2009
Version: current
Fix version: milestone 1
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-131">https://rometools.jira.com/browse/ROME-131</a>
=========================================</pre>
<p>Atom 1.0 Standalone Entry Items are not supported correctly. Right now when<br class="atl-forced-newline" /> parsing an Feed that contains a root "Entry" element rather than a feed element,<br class="atl-forced-newline" /> ROME reads it as a feed object (SyndFeedImpl). This is not correct, and some<br class="atl-forced-newline" /> elements are mapped differently (i.e. Updated field moves to Published date,<br class="atl-forced-newline" /> etc), and some are completely missed out (for example the &lt;content&gt; element.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> To provide further context, I have a feed that has two URIs, one for returning a<br class="atl-forced-newline" /> list of items, and another for returning discrete items. The first service<br class="atl-forced-newline" /> returns a list of entry items, and this works fine. The second returns the entry<br class="atl-forced-newline" /> item, but ROME uses the SyndFeed parser and misses out some information, and<br class="atl-forced-newline" /> also requires me to write extra code since SyndFeed and SyndEntry are not<br class="atl-forced-newline" /> super/sub classes or each other (ie. I would like to use the code I have already<br class="atl-forced-newline" /> written that reads the SyndEntry object in the "List" service implementation).<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> I noted that in 2007, someone else mentioned this problem, and was told that the<br class="atl-forced-newline" /> Atom10Parser class would get a public static method to parse the feed, but this<br class="atl-forced-newline" /> seems to have been removed.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> I suggest adding a Atom10Parser.parseEntry() method, the same as parseFeed. Or<br class="atl-forced-newline" /> enhance parseFeed to check if it is a entry and parse accordingly.</p>

**Comment by PatrickGotthard** [comment]
@imk @snoopdave @farrukhnajmi @mishako I think we should close this issue, this should be a really rare scenario. What do you think?

**Comment by mishako** [comment]
@PatrickGotthard I don't know how widespread stand-alone entries are. If you say it's a rare scenario then let's close the issue.

**Comment by PatrickGotthard** [comment]
I don't even know whether it is valid to use entry as a root element. I'll close this issue...

**Comment by mishako** [comment]
It is valid.
> 4.1.2.  The "atom:entry" Element
> The "atom:entry" element represents an individual entry, acting as a
> container for metadata and data associated with the entry.  This
> element can appear as a child of the atom:feed element, or it can
> appear as the document (i.e., top-level) element of a stand-alone
> Atom Entry Document.

**Comment by olimination** [comment]
As far as I have seen this code is available here: https://github.com/rometools/rome/blob/b91b88f8e9fdc239a2258e4efae06b83dffb2621/rome/src/main/java/com/rometools/rome/io/impl/Atom10Parser.java#L689
