### ISSUE TITLE
Classloader fix under Tomcat

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#146]
<pre>=== This issue was migrated from JIRA ===
Type: Task
Priority: Blocker
Status: Open
Resolution: UNRESOLVED
Reported by: hovis
Assigned to: ROME Jira Lead
Created: Fri Apr 23 13:19:00 CEST 2010
Updated: Thu Sep 15 20:55:40 CEST 2011
Resolved: Fri Apr 23 13:19:46 CEST 2010
Version: current
Fix version: milestone 1
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-145">https://rometools.jira.com/browse/ROME-145</a>
=========================================</pre>
<p>We use Rome within a webapp on Tomcat6 and the properties failed to be found due<br class="atl-forced-newline" /> to the use of Thread.currentThread().getContextClassLoader().<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> In my case the rome.jar is dynamically loaded so<br class="atl-forced-newline" /> Thread.currentThread().getContextClassLoader() will <b>not</b> contain the<br class="atl-forced-newline" /> classloader for rome.jar.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> The patch included fixes this so it always uses the classloader which the Rome<br class="atl-forced-newline" /> jar was loaded by regardless of the classloader the current thread is using.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> Tested the patch outside of Tomcat in a regular simple app and that is fine.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> Also before patching, we tried enabling the fix made for OSGi support, but that<br class="atl-forced-newline" /> was no good either in this situation.</p>

**Comment by mishako** [comment]
This seems to have been fixed in the same way as #130.

**Comment by PatrickGotthard** [comment]
This should be fixed
