### ISSUE TITLE
Problem parsing xml with rome on android

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#155]
<pre>=== This issue was migrated from JIRA ===
Type: Bug
Priority: Major
Status: Open
Resolution: UNRESOLVED
Reported by: mmm286
Assigned to: Unassigned
Created: Thu Apr 07 14:36:15 CEST 2011
Updated: Thu Apr 07 14:36:15 CEST 2011
Resolved: Thu Apr 07 14:36:15 CEST 2011
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-154">https://rometools.jira.com/browse/ROME-154</a>
=========================================</pre>
<p>Hi,<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> I have rome and I'm trying to parse RSS:<br class="atl-forced-newline" /> <a href="http://www.miguiatv.com/rss/tve1.xml" class="external-link" rel="nofollow">http://www.miguiatv.com/rss/tve1.xml</a><br class="atl-forced-newline" /> But when I'm trying to get the Description field:<br class="atl-forced-newline" /> System.out.println("descripcion es ..." + ent.getDescription());<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> Eclipse gives me an error:<br class="atl-forced-newline" /> Could not find class '[Ljava.beans.PropertyDescriptor;', referenced from method com.sun.syndication.feed ....<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> The AVD gives me a FC.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> Could you help me please?<br class="atl-forced-newline" /> Many thanks and sorry for my english!</p>

**Comment by alabeduarte** [comment]
Hi,

Is there someone working on this? I was struggling with this problem as well.

I did some changes, following below:
https://github.com/alabeduarte/rome/commit/3ce5969fb9061cc3be797c4211e8ac1be8b7df4d

Although all tests are passing, I still need to fork rome-fetcher, make it look at my implementation dependency and then test locally through my android app to see how it goes.

Please let me know what your thoughts about it. I'm looking for a RSS tool and this one is a good fit for my purposes.

Thanks

**Comment by grote** [comment]
@alabeduarte one year later now, did you make ROME work with Android or did you end up using another library? If so, which one?

**Comment by alabeduarte** [comment]
Hi @grote 

I end up using an web API to do so.

I'm developing an [podcast client](https://github.com/alabeduarte/mypodcasts-android) so I'm fetching all the feeds I need with this [node.js package](https://github.com/alabeduarte/feedparser-promised) and serve them through this [web API](https://github.com/alabeduarte/mypodcasts-api).

At first I would like to have a way to do this within android stack, but at the end it was easier to maintain keep them separate.

If you have any other experience that you want to share I'll happy to hear it though.

Best!

**Comment by grote** [comment]
Thanks @alabeduarte! Too bad you couldn't make it work with Android. The [app I am working on](https://blog.grobox.de/2016/briar-next-step-of-the-crypto-messenger-evolution/) is p2p, so using servers is out of the question.

**Comment by alabeduarte** [comment]
@grote 

Please let me know if you find out any alternative.

Thanks

**Comment by grote** [comment]
@PatrickGotthard have you looked at https://github.com/alabeduarte/rome/commit/3ce5969fb9061cc3be797c4211e8ac1be8b7df4d and thought about merging this, maybe even before 2.0.0?

**Comment by mishako** [comment]
@grote I don't see why we would want to wait with this change given that it is backwards compatible. Please put it up for review so that we can discuss and decide if it's good or not. One concern I would raise is whether we are allowed to distribute `java.beans.*` code under Apache license.

**Comment by grote** [comment]
@mishako Thanks for chiming in. It is great news that you are principally willing to merge this.

The license is indeed a concern. The code from Oracle and OpenJDK [seem to be licensed](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/a284da808700/src/share/classes/java/beans/WeakIdentityMap.java) under the GPLv2. So that won't work.

There is also [OpenBeans](https://code.google.com/archive/p/openbeans/) which is a redistribution of the `java.beans` package from the [Apache Harmony](https://harmony.apache.org/) project, so it does have the proper license. However, both projects seem to be unmaintained. If that is not a concern for you, we could try if their beans package does the trick as well.

**Comment by grote** [comment]
Somebody seems to maintain a fork of OpenBeans called [android-beans](https://github.com/mini2Dx/android-beans).

**Comment by mishako** [comment]
@grote I'd say we don't care if it is unmaintained, as long as it works.

**Comment by oldosfan** [comment]
The class `java.beans.Introspector` is used by the logging library, and is unavailable on Android, which is causing a hang
