### ISSUE TITLE
No source element in RSS 2.0 items

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#161]
<pre>=== This issue was migrated from JIRA ===
Type: Bug
Priority: Major
Status: Open
Resolution: Unresolved
Environment: JAVA 6, rome 1.0
Reported by: Samuel Santschi
Assigned to: ROME Jira Lead
Created: Mon Dec 12 13:15:48 CET 2011
Updated: Mon Dec 12 13:15:48 CET 2011
Version: current
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-160">https://rometools.jira.com/browse/ROME-160</a>
=========================================</pre>

<p>Hi,</p>

<p>I am aggratating feed in an RSS 2.0.<br/>
i would like to have the source element of all my items set (see sepcs at <a href="http://feed2.w3.org/docs/rss2.html#ltsourcegtSubelementOfLtitemgt" class="external-link" rel="nofollow">http://feed2.w3.org/docs/rss2.html#ltsourcegtSubelementOfLtitemgt</a>)<br/>
for each entry I set the source (entry.setSource(inFeed)<img class="emoticon" src="https://rometools.jira.com/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/> but when I generate my output no source element...</p>

<p>The RSS092Generator populate the feed if item had a source but ConverterForRSS092 don't populate source from the given entry...</p>

**Comment by AdityaAnand1** [comment]
Ahh, I'm trying to get it the other way around, getting the source for a SyndFeed inflated from an external RSS feed.
