### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#163]
<pre>=== This issue was migrated from JIRA ===
Type: New Feature
Priority: Major
Status: Open
Resolution: Unresolved
Reported by: Patrick Julien
Assigned to: ROME Jira Lead
Created: Sat Jan 21 03:36:00 CET 2012
Updated: Sat Jan 21 03:36:00 CET 2012
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-162">https://rometools.jira.com/browse/ROME-162</a>
=========================================</pre>
<p>Support for Android.</p>

<p>There's a port available at</p>

<p><a href="http://android-rome-feed-reader.googlecode.com/" class="external-link" rel="nofollow">http://android-rome-feed-reader.googlecode.com/</a></p>

<p>but the source code has been withheld and it does not include support for any of the modules.</p>

<p>Location of the repository for that project, no source is available<br/>
<a href="http://code.google.com/p/android-rome-feed-reader/source/browse/" class="external-link" rel="nofollow">http://code.google.com/p/android-rome-feed-reader/source/browse/</a></p>

<p>Maven repo, source jar is empty<br/>
<a href="http://android-rome-feed-reader.googlecode.com/svn/maven2/releases/com/google/code/android-rome-feed-reader/android-rome-feed-reader/1.0.0/" class="external-link" rel="nofollow">http://android-rome-feed-reader.googlecode.com/svn/maven2/releases/com/google/code/android-rome-feed-reader/android-rome-feed-reader/1.0.0/</a></p>

**Comment by mishako** [comment]
This issue is too generic and doesn't contain any information on what exactly is the issue. I will close it.

**Comment by jverne** [comment]
Actually, the fork of Rome 1.0 at http://android-rome-feed-reader.googlecode.com/ isn't (or is no longer) portable Android. The current AS/Gradle linter will error out builds because it refs (I recall) three packages not in the Android SDK.

**Comment by mishako** [comment]
@jverne Does Rome 1.7.0 work for you?

**Comment by jverne** [comment]
Is it on jcenter/maven yet? If so, that will be easy to check. Otherwise I'll have to build from scratch.

**Comment by PatrickGotthard** [comment]
Yes, it is on Maven Central yet

**Comment by jverne** [comment]
Gradle linter is still complaining with ROME 1.7.0 from Maven Central, though this time only from the JDOM 2 dependency:
```
C:\Users\jverne\.gradle\caches\modules-2\files-2.1\org.jdom\jdom2\2.0.6\6f14738ec2e9dd0011e343717fa624a10f8aab64\jdom2-2.0.6.jar: Invalid package reference in library; not included in Android: javax.xml.stream.events. Referenced from org.jdom2.input.StAXEventBuilder.
C:\Users\jverne\.gradle\caches\modules-2\files-2.1\org.jdom\jdom2\2.0.6\6f14738ec2e9dd0011e343717fa624a10f8aab64\jdom2-2.0.6.jar: Invalid package reference in library; not included in Android: javax.xml.stream.util. Referenced from org.jdom2.output.support.AbstractStAXEventProcessor.
C:\Users\jverne\.gradle\caches\modules-2\files-2.1\org.jdom\jdom2\2.0.6\6f14738ec2e9dd0011e343717fa624a10f8aab64\jdom2-2.0.6.jar: Invalid package reference in library; not included in Android: javax.xml.stream. Referenced from org.jdom2.input.StAXEventBuilder.
```

**Comment by mishako** [comment]
@jverne I guess this is expected, because not everything in jdom2 is supported by android: https://github.com/hunterhacker/jdom/wiki/JDOM2-and-Android

**Comment by jverne** [comment]
@mishako, yes, this is what it looks like. The problem, as I see it, is that even if JDOM2 is "fully functional" on Android and does not itself refer to these missing classes, I have to hope that nothing in ROME (or anything else that depends on JDOM) doesn't do something that causes `javax.xml.stream` to be reached via JDOM2 classes.

The assumption here is that ROME does **not** use the JDOM "StAX" functionality. If someone can confirm this while I take a look myself, then I can be reasonable sure that I am not shipping with potential `NoClassDefFoundError`

**Comment by jverne** [comment]
A followup: It _appears_ that ROME does not directly access the StAX factory interfaces (which the linter would have mentioned, of course) and a cursory inspection shows that ROME does not instantiation anything in JDOM2 specific to the StAX parser. It looks like JDOM2 is use for SAX style parsing, element walking, etc.

**Comment by mishako** [comment]
@jverne Thanks for looking into it. My cursory inspection yielded the same finding.
