### ISSUE TITLE
new API

### ISSUE THREAD

**Issue by imk** [rometools/rome#173]
Someone (Alejandro Abdelnur, Robert Cooper or ... ?) proposed some [API changes for ROME 2](http://rometools.github.io/rome/ROMEDevelopmentProposals/ROME22ndProposalJuly18th2006CURRENT.html) some years ago, I think, these points are still relevant and this is a good proposal for an API refactoring. One point I would add to the requirements for a new API: It should be easy to use in OSGI environments too (although I haven't any relevant experience in OSGI, this had been an issue in the past).

So what are your oppinions about a new API? I think we should start collecting the requirements, prioritize them and try to find a new (cleaner) API.

**Comment by mishako** [comment]
I think the scope of this issue is to broad and email thread or some other medium would be a better fit for this kind of discussions.
