### ISSUE TITLE
Rome in Maven is out of date

### ISSUE THREAD

**Issue by sigpwned** [rometools/rome#177]
The Rome project has made a lot of progress since the v1.0 was pushed to Maven Central in 2009! Can you do a release of Rome -- like v1.1 or v1.0.1 -- and push it to Maven central?

I'm happy to help, if that would be useful!

**Comment by monksy** [comment]
Also, I would love to see this for the 1.5.1 release. 

Without it, we're stuck with v1.0.

**Comment by PatrickGotthard** [comment]
Hi monksy,

ROME 1.5.1 is already on Maven Central. Note that the GroupID changed in version 1.5.0.

Regards,
Patrick

**Comment by monksy** [comment]
Oops.. Didn't know about that. Thanks for your help!
