### ISSUE TITLE
no set/get methods for width/height in SyndImage class

### ISSUE THREAD

**Issue by olalob** [rometools/rome#189]
missing methods for image width and height. if an image is set for rss channel, it gets for width and height the default value -1, which is not valid. the W3C feed validator reports the errors:
- width must be between 1 and 144
- height must be between 1 and 400

please fix it. to upgrade are:
- com.rometools.rome.feed.synd.SyndImage
- com.rometools.rome.feed.synd.SyndImageImpl
- com.rometools.rome.feed.synd.impl.ConverterForRSS090#createRSSImage(final SyndImage sImage)

thanks.

**Comment by tombujok** [comment]
Any hints?

**Comment by mishako** [comment]
> Shouldn't be much work. I will provide a fix by the end of this week.

:-D

This seems to have been fixed in #194 and #201 though.

**Comment by mishako** [comment]
Closing this. Please speak up if you don't agree.

**Comment by mishako** [comment]
@olalob @ChristianBusch @tombujok Rome 1.6.0 has been released with this issue fixed.
