### ISSUE TITLE
Upgrade to JDOM 2.0.5

### ISSUE THREAD

**Issue by Athou** [rometools/rome#197]
See https://github.com/hunterhacker/jdom/issues/112

Note that artifactId changed from `jdom` to `jdom2`.

**Comment by PatrickGotthard** [comment]
The latest version of JDOM 2 will be used in Version 1.6.0

**Comment by mschipperheyn** [comment]
Any ETA on 1.6.0? Sucks being stuck on dangerous basecode

**Comment by mschipperheyn** [comment]
Any updates? Bueller, Bueller?

**Comment by mishako** [comment]
This is weird. Patrick has switched to `jdom2` in commit https://github.com/rometools/rome/commit/0b9df0e84ae40265108a28f53151559c938c9efd. Several months later Rome 1.5.1 has been released. Quite surprisingly it still depends on `jdom` [1].

@PatrickGotthard Are you sure your release workflow is not broken?

[1] http://search.maven.org/#artifactdetails%7Ccom.rometools%7Crome%7C1.5.1%7Cjar

**Comment by mishako** [comment]
Sorry, I was confused. Rome 1.5.1 was released from a separate branch.

@mschipperheyn I expect Rome 1.6.0 to be released within a month.

**Comment by mishako** [comment]
@Athou @mschipperheyn Rome 1.6.0 has been released with this issue fixed.
