### ISSUE TITLE
Add OSGi Manifest headers in 1.5.x again

### ISSUE THREAD

**Issue by sewe** [rometools/rome#204]
ROME 1.0 has OSGi headers in its `MANIFEST.MF` (at least for `rome:rome:1.0`, although not for `rome:rome-fetcher:1.o`), but the most recent `com.rometools:rome:1.51` has not. Why?

**Comment by PatrickGotthard** [comment]
This will be fixed in #216

**Comment by mishako** [comment]
@sewe Rome 1.6.0 has been released with this issue fixed.
