### ISSUE TITLE
DateParser's parseRFC822 method does not properly handle a UTC timezone

### ISSUE THREAD

**Issue by jimmorgan** [rometools/rome#205]
The parseRFC822 method in com.rometools.rome.io.impl.DateParser does not correctly handle date strings with a UTC timezone.  For example, the following value:
    `Sat, 7 Mar 2015 0:30:37 UTC`
is internally converted to:
    `Sat, 7 Mar 2015 0:30:37 GMTC`
and does not properly parse to a Date.

One possible solution would be to check if 'UTC' is present (or ends with 'UTC') and replace it with 'UT' (or 'GMT').

**Comment by mishako** [comment]
RFC 822[1] doesn't allow UTC timezone, so `Sat, 7 Mar 2015 0:30:37 UTC` is not a valid RFC 822 date. However that `GMTC` you mentioned looks more like a bug and less like a "not allowed" feature. Also would be interesting to know where this RFC 822 date with `UTC` comes from. Where did you find it?

[1] http://www.w3.org/Protocols/rfc822/#z28

**Comment by mishako** [comment]
@jimmorgan Rome 1.6.0 has been released with this issue fixed.
