### ISSUE TITLE
Trim whitespace when setting update period

### ISSUE THREAD

**Issue by freemarmoset** [rometools/rome#207]
SyModuleImpl compares this text to constant strings in hash when setting the update period. If there's whitespace, an IllegalArgument exception is currently thrown because the text doesn't match exactly. Whitespace should be irrelevant here. Period should be trimmed the same way frequency is here.

https://github.com/rometools/rome/pull/206

**Comment by PatrickGotthard** [comment]
Hi freearmoset,

as far as I understand this was fixed with #206?
Please reopen this issue when this isn't correct.

Regards,
Patrick
