### ISSUE TITLE
fetcher should expose wether conditional get had 304 response. 

### ISSUE THREAD

**Issue by RuedigerMoeller** [rometools/rome#209]
Current logic of fetcher is to always return a full feed entry, in case retrieving data from a cache. 
For large amounts of feeds (several 100k to millions), this requires huge caches.
For many applications it would be prefereable if one could pass in last-modified date to the "retrieveFeed" method and only get a result in case conditional get was not successful.
This way the application needs to cache the last modified date per feed only.

**Comment by mishako** [comment]
@RuedigerMoeller 
I guess one of the popular http client libraries (e.g. Apache's or Google's) would be a better fit for this job. Personally I think that Rome Fetcher should be deprecated. Is there a reason why you would prefer Fetcher over the aforementioned http libraries?

As a side note, millions of feeds is pretty impressive! Good to hear that Rome is used on that scale.

**Comment by RuedigerMoeller** [comment]
yeah we switched to async http, there are multiple issues with fetcher at scale ;)
