### ISSUE TITLE
[New] [Req] Allow configuration of ignoring optional channel elements when broken

### ISSUE THREAD

**Issue by nea** [rometools/rome#210]
Hi

I am currently fooling around with ROME and am pretty impressed and happy with everything given.

But now I have an obviously broken feed that contains an <image> element in <channel> only with a URL, no image, no title. So, by specification these are required and therefore ROME breaks, and that is totally correct.

What I would like to know if it would make sense to provide an option, global or per call that would ignore or change errors to warnings of optional elements (i.e. https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements) such as <image> by specification. By that, the given feed could be parsed if I want it to, just skipping that element.

Is there already something like that or would it make sense to add it? If it would be seen as helpful, I would also try to provide the according pull-request, contribute as much as I can.

Thanks and Cheers

**Comment by mishako** [comment]
@nea 
Could you please specify how exactly the broken feed looks like and how exactly does Rome break?

I tried to parse this XML
```
<?xml version="1.0"?>
<rss version="2.0">
  <channel>
    <image>
      <url>http://example.org/image.png</url>
    </image>
  </channel>
</rss>
```

with this code
```
SyndFeed feed = new SyndFeedInput().build(new XmlReader(...));
System.out.println(feed.getImage().getUrl());
```

and it works perfectly fine, printing `http://example.org/image.png`.

**Comment by mishako** [comment]
@nea Any thoughts?

**Comment by PatrickGotthard** [comment]
Eventually we really should implement a "relaxed" parser for such cases. 

Probably related to #186

**Comment by mishako** [comment]
@PatrickGotthard Isn't Rome already relaxed for this particular case? As in the example I gave above, it just ignores missing required elements as if they were optional.

**Comment by PatrickGotthard** [comment]
Okay, I think the parser should be as lenient as possible but we should ensure that generated feeds are always valid
