### ISSUE TITLE
[utils] All java source files are without license headers

### ISSUE THREAD

**Issue by mishako** [rometools/rome#220]
<a href="https://github.com/puntogil"><img src="https://avatars.githubusercontent.com/u/3623999?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [puntogil](https://github.com/puntogil)**
_Thursday Jan 21, 2016 at 17:47 GMT_
_Originally opened as https://github.com/rometools/rome-utils/issues/2_

----

Hi,
Please, add license headers and confirm the licensing of code and/or content/s
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
This issue block https://bugzilla.redhat.com/show_bug.cgi?id=1185275
Thanks in advance

**Comment by mishako** [comment]
Fixed in https://github.com/rometools/rome-utils/pull/3
@puntogil

**Comment by puntogil** [comment]
Thanks!
