### ISSUE TITLE
[fetcher] HTTP header field user-agent not set

### ISSUE THREAD

**Issue by mishako** [rometools/rome#233]
<a href="https://github.com/Joerg-Schoemer"><img src="https://avatars.githubusercontent.com/u/8568035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Joerg-Schoemer](https://github.com/Joerg-Schoemer)**
_Monday Dec 15, 2014 at 14:47 GMT_
_Originally opened as https://github.com/rometools/rome-fetcher/issues/16_

----

The HTTP header field user-agent can not be set when cache is used.

**Comment by PatrickGotthard** [comment]
I'm unable to reproduce the issue using this code:
```
import java.net.URL;

import com.rometools.fetcher.impl.HashMapFeedInfoCache;
import com.rometools.fetcher.impl.HttpURLFeedFetcher;

public class UserAgentTest {

    public static void main(String[] args) throws Exception {
        
        URL url = new URL("http://localhost:8080/");
        
        HashMapFeedInfoCache cache = new HashMapFeedInfoCache();
        
        HttpURLFeedFetcher fetcher = new HttpURLFeedFetcher(cache);
        fetcher.setUserAgent("test");
        fetcher.retrieveFeed("foo", url);
        fetcher.retrieveFeed("bar", url);
        fetcher.retrieveFeed(url);
        fetcher.retrieveFeed(url);
        
        
    }
    
}
```

I wrote a simple HttpServer that prints out the UserAgent. The console displays

> foo
> bar
> test
> test
