### ISSUE TITLE
[modules] rdfs:seeAlso resources

### ISSUE THREAD

**Issue by mishako** [rometools/rome#238]
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Monday Sep 30, 2013 at 15:39 GMT_
_Originally opened as https://github.com/rometools/rome-modules/issues/5_

---

<pre>=== This issue was migrated from JIRA ===
Type: New Feature
Priority: Major
Status: Open
Resolution: Unresolved
Reported by: Robert Cooper
Assigned to: Robert Cooper
Created: Fri Apr 01 22:12:49 CEST 2011
Updated: Fri Apr 01 22:12:49 CEST 2011
JIRA Link: <a href="https://rometools.jira.com/browse/MODULES-4">https://rometools.jira.com/browse/MODULES-4</a>
=========================================</pre>

<p>Hi,</p>

<p>I'd like to create a feed containing something like this:</p>

<p>&lt;rss:item rdf:about="#foo"&gt;<br/>
       ...<br/>
       &lt;rdfs:seeAlso rdf:resource="http://sun.com/"/&gt;<br/>
       ...<br/>
&lt;/rss:item&gt;</p>

<p>I've only seen String, List (of Strings) and Dates as<br/>
data types.  Is it possible to add a URI and have the<br/>
URI serialised as in the example above?</p>

<p>Best regards,<br/>
Andreas.</p>

**Comment by PatrickGotthard** [comment]
I'm closing this issue - 7 years old and no further comments
