### ISSUE TITLE
[modules] add a few fields to iTunes module

### ISSUE THREAD

**Issue by mishako** [rometools/rome#244]
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Monday Sep 30, 2013 at 15:39 GMT_
_Originally opened as https://github.com/rometools/rome-modules/issues/11_

---

<pre>=== This issue was migrated from JIRA ===
Type: New Feature
Priority: Major
Status: Open
Resolution: Unresolved
Reported by: Kevin Horan
Assigned to: Robert Cooper
Created: Fri Dec 28 05:25:09 CET 2012
Updated: Fri Dec 28 05:25:09 CET 2012
JIRA Link: <a href="https://rometools.jira.com/browse/MODULES-10">https://rometools.jira.com/browse/MODULES-10</a>
=========================================</pre>

<p>I have been using your iTunes module to develop a podcast. There <br/>
are a few fields I would like to use though that aren't present, at the <br/>
Entry level. These are the "image" tag (A URL), the "order" tag (an <br/>
int), and the ability to set "explicit" to "clean" (makes iTunes display <br/>
a certain icon I guess). The following two tags would also be useful, <br/>
but not required: "complete" (Boolean), and "new-feed-url" (URL).<br/>
     I'd be happy to makes these changes myself. I'm not <br/>
very familiar with contributing to projects, so let me know how best to <br/>
help.</p>

**Comment by mishako** [comment]
<a href="https://github.com/imk"><img src="https://avatars.githubusercontent.com/u/1017015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [imk](https://github.com/imk)**
_Sunday Apr 20, 2014 at 18:03 GMT_

----

added missing itunes tags and extended an existing tag (incompatible to
previous version, changed boolean to enum), see https://github.com/rometools/rome-modules/tree/itunes-update

**Comment by mishako** [comment]
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Saturday Jul 12, 2014 at 09:28 GMT_

----

@imk: I've just merged the latest changes to your branch. Would you like to review my changes and merge your branch back to master? Especially have a look at ITunesGeneratorTest class, currently the testEndToEnd test fails.

**Comment by mishako** [comment]
<a href="https://github.com/erd"><img src="https://avatars.githubusercontent.com/u/184194?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [erd](https://github.com/erd)**
_Friday Oct 10, 2014 at 03:33 GMT_

----

Any chance these changes can be merged? It would be great to have more complete iTunes parsing.

**Comment by mishako** [comment]
<a href="https://github.com/claym"><img src="https://avatars.githubusercontent.com/u/230486?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [claym](https://github.com/claym)**
_Monday Sep 21, 2015 at 13:11 GMT_

----

Were these changes ever merged? I have need of the image tag support.

**Comment by mishako** [comment]
<a href="https://github.com/mishako"><img src="https://avatars.githubusercontent.com/u/202554?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mishako](https://github.com/mishako)**
_Tuesday Dec 08, 2015 at 19:38 GMT_

----

Most of this has been recently fixed in #37, except for the `clean` value of the `explicit` tag.

Adding `clean` value is a breaking change. I don't want to do breaking changes without a roadmap and a separate branch for the next major version. Otherwise any merged change will end up in the next minor or patch release.

By the way, maybe it's time to do a minor release? What do you think? @snoopdave @PatrickGotthard

**Comment by mishako** [comment]
<a href="https://github.com/mishako"><img src="https://avatars.githubusercontent.com/u/202554?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mishako](https://github.com/mishako)**
_Friday Dec 18, 2015 at 14:38 GMT_

----

@PatrickGotthard Any thoughts on doing a minor release?

**Comment by PatrickGotthard** [comment]
We have to check whether the new fields were already included in v1.5. In this case we should solve this issue in v1.7, otherwise we can merge the branch and solve this issue in v1.6

**Comment by mishako** [comment]
@PatrickGotthard I thought I had added the fields in 91d8ea1. Where does your branch (`ROME-244-itunes-update`) come from?

**Comment by PatrickGotthard** [comment]
I transfered the changes from a branch of the rome-modules project. Obviously two people implemented this changes seperately, but the changes from the branch seem a little bit better to me.

**Comment by mishako** [comment]
Let's put it up for review? I have some remarks. Starting with that some of the files have every line changed. Looks like it adds carriage returns:
```
$ head -n 1 AbstractITunesObject.java | od -c
0000000    /   *  \r  \n
```

**Comment by mishako** [comment]
@erd @claym Rome 1.6.0 has been released with this issue mostly fixed (except for the `clean` value of the `explicit` tag).

**Comment by razyalov** [comment]
Any plans on adding the new itunes tags 'itunes:type', the episode's 'itunes:season', 'itunes:episode' and 'itunes:episodeType'?

**Comment by mishako** [comment]
Apparently there was some confusion regarding `itunes:explicit` tag values that we need to support. What I said earlier is not true:

> Adding clean value is a breaking change. I don't want to do breaking changes without a roadmap and a separate branch for the next major version. Otherwise any merged change will end up in the next minor or patch release.

I made the change and it's not breaking backward compatibility. I will release a new version.

**Comment by PatrickGotthard** [comment]
Hi @mishako,

would you like to have a look at the branch for this issue? https://github.com/rometools/rome/compare/ROME-244-itunes-update

I don't know whether the implementation of the branch is better than the current implementation. We should merge it when it's better, or delete the branch otherwise.

Regards,
Patrick

**Comment by PatrickGotthard** [comment]
I'm closing this issue now - please open a new issue when there are further fields missing.
