### ISSUE TITLE
[modules] Does ROME supports parser for "Media RSS" version 1.5.0

### ISSUE THREAD

**Issue by mishako** [rometools/rome#248]
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Friday Oct 04, 2013 at 12:32 GMT_
_Originally opened as https://github.com/rometools/rome-modules/issues/15_

---

<pre>=== This issue was migrated from JIRA ===
Type: New Feature
Priority: Critical
Status: Open
Resolution: Unresolved
Reported by: Mani
Assigned to: ROME Jira Lead
Created: Thu Nov 17 10:50:25 CET 2011
Updated: Sun Nov 20 06:46:11 CET 2011
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-159">https://rometools.jira.com/browse/ROME-159</a>
=========================================</pre>

<p>Hi,</p>

<p>ROME tools is an excellent parser api for RSS / Atom Feeds.</p>

<p>But I have requirement to parse "Media RSS" latest version 1.5.0. Will the existing parser supports my requirement, if not is there any future development based on this version ?</p>

<p>Thanks.</p>

**Comment by mishako** [comment]
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Friday Oct 04, 2013 at 12:33 GMT_

----

<pre>=== This comment was migrated from JIRA ===
Author: devarajaswami
Created: Sun Nov 20 06:46:11 CET 2011
===========================================</pre>
<p>I have the same problem. Rome 1.0 currently does not seem to parse some of the new tags in MediaRSS 1.5.<br/>
Since MediaRSS 1.5 came out on 09/09/2009, most of the public Media RSS feeds have started using these new tags. Wondering if there are any plans to upgrade Rome to parse Media RSS 1.5? </p>

**Comment by mishako** [comment]
<a href="https://github.com/imk"><img src="https://avatars.githubusercontent.com/u/1017015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [imk](https://github.com/imk)**
_Friday Apr 18, 2014 at 20:12 GMT_

----

Changes for MediaRSS 1.5 (from http://www.rssboard.org/media-rss)

* Added `<media:community>` element for adding community content like ratings, tags, etc.
* Added `<media:comments>` element for adding user comments.
* Added `<media:embed>` element for adding player-specific embed code.
* Added `<media:responses>` element for adding media responses to a particular media object.
* Added `<media:backLinks>` element for adding links pointing to a media object.
* Added `<media:status>` element for maintaining the state of a feed -- whether the feed is still active, or it has been removed/blocked by the publisher.
* Added `<media:license>` element for specifying the licensing information of a media object.
* Added `<media:price>` element for specifying the pricing information of a media object.
* Added `<media:subTitle>` element for specifying the subtitles of a media object.
* Added `<media:peerLink>` element for specifying the P2P link to a media object.
* Added `<media:location>` element for specifying various locations conforming to geoRSS.
* Added `<media:rights>` element for specifying the rights information about a media object.
* Added `<media:scenes>` element for including scene specific information from a media object.
* Added option for allowing/denying sharing of a media object in `<media:restriction>` element.

The namespace didn't change, so there can't be different modules for MediaRSS 1.5 and other MediaRSS versions, when in need of older version of MediaRSS, user should not use those new elements.

**Comment by mishako** [comment]
<a href="https://github.com/imk"><img src="https://avatars.githubusercontent.com/u/1017015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [imk](https://github.com/imk)**
_Sunday Apr 20, 2014 at 14:55 GMT_

----

support for new elements in MediaRSS 1.5.1 added to branch https://github.com/rometools/rome-modules/tree/media-rss-1.5.1 - didn't wanted to do so many changes while trying to finish a new release.

**Comment by mishako** [comment]
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Saturday Jul 12, 2014 at 09:26 GMT_

----

@imk: I've just merged the latest changes to your branch. Would you like to review my changes and merge your branch back to master?

**Comment by mishako** [comment]
<a href="https://github.com/brianmacdonald"><img src="https://avatars.githubusercontent.com/u/40810?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brianmacdonald](https://github.com/brianmacdonald)**
_Thursday Sep 03, 2015 at 15:35 GMT_

----

@PatrickGotthard @imk: What is the status of this being merged back to master?

**Comment by PatrickGotthard** [comment]
This MediaRSS changes from this branch have to be merged: https://github.com/rometools/rome-modules/tree/media-rss-1.5.1

**Comment by PatrickGotthard** [comment]
I've moved the support for MediaRSS to the next version because we are planning to release ROME 1.6.0 soon. We will try to release version 1.7 quickly afterwards inclusing support for MediaRSS 1.5.1.

**Comment by snursmumrik** [comment]
Have the MediaRSS 1.5.1 changes been merged to the main branch of rometools? I do not see them.
