### ISSUE TITLE
com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 1: Premature end of file.

### ISSUE THREAD

**Issue by pubmikeb** [rometools/rome#266]
I'm trying to fetch the content of the RSS feeds with ROME tools 1.5.1 from http://emm.newsbrief.eu news aggregation system.

I pad attention that ROME returns exception «**_com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 1: Premature end of file_**» on some of the links.

The problematic part of the code, which leads the exception:
```
// fetch data from URL
SyndFeedInput input = new SyndFeedInput();
SyndFeed feed = null;
try {
	feed = input.build(new XmlReader(feedSource));
} catch (FeedException | IOException | NullPointerException e) {
	isOK = false;
	e.printStackTrace();
	System.out.println(dataSource);
	System.out.println(e.getMessage());
}
```

Try to re-run the code multiple times, you'll see that this issue appears for the different links, and from the time to time all the links return error but sometimes there is no even one error.

From my observations, if you re-run the code multiple times in a row, the probability that the bug will arise is less than if you re-run the code with a long break/pause.

The full error text:

> com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 1: Premature end of file.
> 	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:237)
> 	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:154)
> 	at Rome.getRSSData(Rome.java:29)
> 	at Main.main(Main.java:38)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> Caused by: org.jdom2.input.JDOMParseException: Error on line 1: Premature end of file.
> 	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
> 	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
> 	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
> 	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:234)
> 	... 8 more
> Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
> 	at 

com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
> 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
> 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
> 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
> 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
> 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
> 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
> 	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)

**Comment by jotomo** [comment]
```
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
```
The 'file' is empty, because - most likely - fetching the URL didn't work. Fetching URLs via the _URL_ class is a bit brittle. Usually in all but the most trivial cases something like Apache HttpClient is used to fetch a document, handle possible errors and then hand the content over to Rome for parsing. The service you're querying could be blocking your requests because you're querying it too often. If you use HttpClient you can check not only the content, but also what HTTP status code the site returned, like _429 Too Many Requests_. HTH.

**Comment by pubmikeb** [comment]
@jotomo ,
Thank you for the tip, suppose, I'm using **_Apache HttpClient_** to fetch the page content, how should I pass it to ROME? Currently I'm using `new XmlReader();`, which should receive an URL object. So, even if I fetch the page with HttpClient, ROME still needs URL object, right?

**Comment by PatrickGotthard** [comment]
@pubmikeb 

no, you don't need the URL object. SyndFeedInput is able to handle several input types. Please have a look at the multiple overloaded SyndFeedInput#build methods.

Regards,
Patrick

**Comment by pubmikeb** [comment]
@PatrickGotthard ,

I've re-implemented the fetcher module with Apache HttpClient 4.5.1:

	private static BufferedReader sendGET(String dataSource) throws IOException {

		HttpGet httpGet = new HttpGet(dataSource);
		httpGet.addHeader("User-Agent", ConfigValues.getRandUA());

		CloseableHttpClient httpClient = HttpClients.createDefault();
		CloseableHttpResponse httpResponse = httpClient.execute(httpGet);

		BufferedReader reader;

		if (httpResponse.getStatusLine().getStatusCode() == HttpStatus.SC_OK) {
			reader = new BufferedReader(new InputStreamReader(httpResponse.getEntity().getContent()));
		} else {
			reader = null;
		}

		String inputLine;
		StringBuffer response = new StringBuffer();

		while ((inputLine = reader.readLine()) != null) {
			response.append(inputLine);
		}

		//reader.close(); temp code, should be refactored
		httpClient.close();

		return reader;
	}

everything is working but when I'm trying to push the feed's content to `SyndFeedInput#build`:

	// fetch data from URL
	SyndFeedInput input = new SyndFeedInput();
	SyndFeed feed = null;

	try {
		//feed = input.build(new XmlReader(feedSource));
		feed = input.build(sendGET(dataSource));
	} catch (FeedException | IOException e) {
		e.getMessage();
	}

I get exception **_com.rometools.rome.io.ParsingFeedException : Invalid XML_**:

> com.rometools.rome.io.ParsingFeedException: Invalid XML
> 	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:241)
> 	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:154)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk
> 	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:255)
> 	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
> 	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
> 	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:215)
> 	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:316)
> 	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:140)
> 	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
> 	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
> 	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:227)
> 	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:136)
> 	at org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:97)
> 	at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
> 	at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
> 	at java.io.InputStreamReader.close(InputStreamReader.java:199)
> 	at java.io.BufferedReader.close(BufferedReader.java:525)
> 	at com.rometools.rome.io.impl.XmlFixerReader.close(XmlFixerReader.java:383)
> 	at com.sun.xml.internal.stream.Entity$ScannedEntity.close(Entity.java:422)
> 	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1388)
> 	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1814)
> 	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipSpaces(XMLEntityScanner.java:1538)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:838)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
> 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
> 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
> 	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
> 	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
> 	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
> 	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:234)

The example of feed URL:
http://emm.newsbrief.eu/rss?type=story&id=straitstimesSG-faa0591b1e76d35a308e8ded4666f7e8.20160220.en&duplicates=false

Is it bug or what I'm doing wrong?

**Comment by jotomo** [comment]
@pubmikeb The feed itself is valid, I can parse it here with Rome. If you look closer at the stracktrace you see the cause is ``` Caused by: org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk```, so the error happens with HttpClient code.
The variable _reader_: if the status code is anything but _OK_, you'll get a NPE, obvisouly. More importantly, you iterate over it in your code, thereby exhausting the InputStream. When you return _reader_ it should be empty. Were you trying to copy the data to _response_ and meant to return _response.toString_? Note that the data is altered: your're removing newlines. You could just return _reader_ after the _if_ block. Not sure if calling _httpClient.close()_ can cause trouble if the _reader_ is read from afterwards. If you have more than just on GET you might initialize the HttpClient outside of the method and store it in a field.
P.S. To test, I just downloaded the RSS feed and used _new SyndFeedInput().build(new File(...))_ to verify the feed's valid.

**Comment by pubmikeb** [comment]
@jotomo ,
Thanks for the comment. You was right, the problem was with the HttpClient code, actually I should not call `httpClient.close()` before I finish to work with the `reader`. I updated the code (in the previous comment) and it's working fine.

I'll deploy the new code to the internal server and will let you know if the initial issue (Invalid XML: Error on line 1: Premature end of file) still persists.

**Comment by pubmikeb** [comment]
I tested the new code on a server, there is no **_Invalid XML: Error on line 1: Premature end of file_** error anymore. One more question: the server frequently returns the HTTP Status #304. In order to prevent receiving this status I added header: `httpGet.setHeader(new BasicHeader("Cache-Control", "no-cache, no-store, must-revalidate"));` but it doesn't stop the server to return a code #304. Is there any way to avoid this HTTP status code?

**Comment by jotomo** [comment]
Why don't you check for that code and skip the feed processing? 304 says the feed content is unchanged so there's no need to re-transmit or re-parse the feed. Using curl I don't see any ETags or If-Modified header, so it could be the server determining to you already have a recent copy to reduce load. If I remember correctly the site stated feeds are updated every 10m. How often do you check? Did you check their API docs, they should define what they expect of well-behaving clients.

**Comment by pubmikeb** [comment]
I'm checking every 20 minutes, but not all feeds are updated.
Do I understand correctly that `httpGet.setHeader(new BasicHeader("Cache-Control", "no-cache, no-store, max-age=0, must-revalidate, private"));` will not prevent the server to return 304?

**Comment by jotomo** [comment]
It would appear the Cache-Control header has no influence in this case. Though I'm guessing here, there are a lot of details going with caching and I don't know what the default behaviour of HttpClient is. The URL contains a ID parameter, which the server could use to infer if the content has checked for you. Again, the API docs should specify this. Also, again, what's wrong with a 304 status code? It's a perfectly legal response. If you need a full listing for every iteration just keep a copy of the last 200 response.

**Comment by pubmikeb** [comment]
OK.
Again, special thanks to @PatrickGotthard and @jotomo for the help.
