### ISSUE TITLE
Outdated website rometools.github.io/rome

### ISSUE THREAD

**Issue by leoarnold** [rometools/rome#281]
Dear ROME developers,

I used to think that the ROME project was abandoned, because the GitHub page

http://rometools.github.io/rome/

was the first result on a Google search. The page was last updated in 2014, references `com.sun.syndication` and talks a lot about versions prior to 1.0.

**Comment by mishako** [comment]
Hi Leo. Thanks for bringing this up. Do you have any suggestions on what we should do? Looks like a lot of work to rewrite all pages, but we probably don't want to delete everything either.

**Comment by leoarnold** [comment]
Oh, I see. Well, keeping this issue open should be good, so it shows up in Google for clarification.

Maybe it's possible to clone the website (with, say, `wget -r`) and then reopen the corresponding GitHub pages repo, push that content and hope for improvements via pull requests?

**Comment by mishako** [comment]
Thanks for the suggestion! Luckily the contents of the website are already in the repo https://github.com/rometools/rome/tree/master/rome/src/site

**Comment by leoarnold** [comment]
Reading a little bit further into it, I found out that the website serves the content from your `gh-pages` branch, which was last updated/synced in 2014 by @imk.

**Comment by PatrickGotthard** [comment]
The contents can be generated from the sources mishako referenced above. But we have to merge the docs of all projects since we have merged all projects into one repository. Also the documentation is really outdated. We definetely have to spend some time to cleanup and updste the documentation.

**Comment by mishako** [comment]
Please review #297. The biggest change there is combining all sites into one, but I also did some cleanup to make the site look less outdated.

**Comment by mishako** [comment]
I updated the website. It looks much better now. Closing the issue.
