### ISSUE TITLE
ROME 1.6.0 on Maven's repositories

### ISSUE THREAD

**Issue by pubmikeb** [rometools/rome#282]
I see ROME has been updated to 1.6.0 and it's a great news but when the new version will appear on Maven's servers and will be available to automatic downloading?

**Comment by PatrickGotthard** [comment]
Good question. There must be something wrong, I have released the artifacts from Sonatype's staging area directly after building the release. I don't know why it hasn't been synced to Maven central.

**Comment by pubmikeb** [comment]
IDEA demonstrates links to ROME 1.6.0, 1.7.0 and 2.0.0 snapshots but can't fetch the JARs.

**Comment by mishako** [comment]
@PatrickGotthard 
Maybe this can help?

>  Once you have successfully closed the staging repository, you can release it by pressing the Release button. This will move the components into the release repository of OSSRH where it will be synced to the Central Repository.

http://central.sonatype.org/pages/releasing-the-deployment.html

**Comment by pubmikeb** [comment]
Can you, please, fix the issue with the release on Maven's servers?
It will be great to be able to automatically update to the latest version of ROME via Maven's infrastructure.

**Comment by PatrickGotthard** [comment]
Sorry, I was very busy the last days and had no time to look at the problem. ROME 1.6.0 should be available on Maven Central soon. I forgot to press the release button after closing the staging repository and had to rebuild version 1.6.0 to be able to deploy it to Maven Central.

**Comment by pubmikeb** [comment]
Many thanks! Version 1.6.0 is already on Maven's servers.
Just one moment, currently ROME 1.6.0 has _slf4j-api-1.7.1**6**_ in its dependencies, while the latest version is _slf4j-api-1.7.1**9**_. Is there any reason why ROME uses the specific minor version of _slf4j-api_?

**Comment by mishako** [comment]
So, Rome is 3 patch versions behind? Seems pretty up-to-date to me. What do you think?

**Comment by PatrickGotthard** [comment]
I've updated all dependencies on February, 20. At this time slf4j-api 1.7.16 was the latest version: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.slf4j%22%20AND%20a%3A%22slf4j-api%22
