### ISSUE TITLE
Files with license problem

### ISSUE THREAD

**Issue by puntogil** [rometools/rome#288]
Hi
The following source files are without license headers:

./rome-propono/src/main/java/com/rometools/propono/blogclient/metaweblog/NoOpIterator.java
./rome-propono/src/main/java/com/rometools/propono/atom/server/ConfigurationError.java
./rome-propono/src/site/resources/css/site.css
./rome/src/main/java/com/rometools/rome/io/impl/NumberParser.java
./rome/src/main/java/com/rometools/rome/io/impl/PropertiesLoader.java
./rome/src/main/java/com/rometools/rome/io/impl/BaseWireFeedGenerator.java
./rome/src/main/java/com/rometools/rome/io/impl/BaseWireFeedParser.java
./rome/src/main/java/com/rometools/rome/io/SAXBuilder.java
./rome/src/main/java/com/rometools/rome/io/DelegatingModuleParser.java
./rome/src/main/java/com/rometools/rome/io/DelegatingModuleGenerator.java
./rome/src/main/java/com/rometools/rome/io/XmlReaderException.java
./rome/src/main/java/com/rometools/rome/feed/impl/ConfigurableClassLoader.java
./rome/src/main/java/com/rometools/rome/feed/synd/SyndEnclosure.java
./rome/src/main/java/com/rometools/rome/feed/synd/SyndEnclosureImpl.java
./rome/src/main/java/com/rometools/rome/feed/synd/impl/URINormalizer.java
./rome/src/main/java/com/rometools/rome/feed/synd/SyndCategoryListFacade.java

./rome/src/test/java/com/rometools/rome/io/impl/RSS20ParserTest.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsAtom10.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS091N.java
./rome/src/test/java/com/rometools/rome/unittest/TestAtomContent.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS093.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS20.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS090.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedAtom10Bray.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS091U.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS10DCMulti.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsAtom03.java
./rome/src/test/java/com/rometools/rome/unittest/TestXmlBomb.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS094.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedAtom10prefix.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS091N.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS094.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedAtom10b.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS092Alt.java
./rome/src/test/java/com/rometools/rome/unittest/issues/Issue131Test.java
./rome/src/test/java/com/rometools/rome/unittest/issues/Issue88Test.java
./rome/src/test/java/com/rometools/rome/unittest/issues/Issue158Test.java
./rome/src/test/java/com/rometools/rome/unittest/issues/Issue137Test.java
./rome/src/test/java/com/rometools/rome/unittest/issues/Issue161Test.java
./rome/src/test/java/com/rometools/rome/unittest/issues/Issue162Test.java
./rome/src/test/java/com/rometools/rome/unittest/issues/Issue134Test.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedAtom10.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS092.java
./rome/src/test/java/com/rometools/rome/unittest/TestEqualsBean.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS091U.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedAtom03DCSyModules.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS090.java
./rome/src/test/java/com/rometools/rome/unittest/TestBase64.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS093.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS092.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS10.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedAtom03.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedRSS10DCSyModules.java
./rome/src/test/java/com/rometools/rome/unittest/TestSyndFeedAtom10Ruby.java
./rome/src/test/java/com/rometools/rome/unittest/FeedOpsTest.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS20.java
./rome/src/test/java/com/rometools/rome/unittest/TestDublinCore.java
./rome/src/test/java/com/rometools/rome/unittest/FeedTest.java
./rome/src/test/java/com/rometools/rome/unittest/TestOpsRSS10.java
./rome/src/test/java/com/rometools/rome/unittest/SyndFeedTest.java
./rome/src/site/resources/css/site.css

./rome-opml/src/main/java/com/rometools/opml/io/impl/OPML20Generator.java
./rome-opml/src/main/java/com/rometools/opml/feed/synd/impl/TreeCategoryImpl.java
./rome-opml/src/main/java/com/rometools/opml/feed/synd/impl/ConverterForOPML20.java

./rome-opml/src/test/java/com/rometools/opml/TestOpsOPML10links.java
./rome-opml/src/test/java/com/rometools/opml/io/impl/OPML20GeneratorTest.java
./rome-opml/src/test/java/com/rometools/opml/TestOpsOPML20.java
./rome-opml/src/test/java/com/rometools/opml/test/NullWriter.java
./rome-opml/src/test/java/com/rometools/opml/test/TestUtil.java
./rome-opml/src/test/java/com/rometools/opml/TestOpsOPML10.java
./rome-opml/src/test/java/com/rometools/opml/FeedOpsTest.java
./rome-opml/src/test/java/com/rometools/opml/FeedTest.java
./rome-opml/src/test/java/com/rometools/opml/SyndFeedTest.java
./rome-opml/src/site/resources/css/site.css

./rome-certiorem/src/main/java/com/rometools/certiorem/hub/DeltaSyndFeedInfo.java
./rome-certiorem/src/main/java/com/rometools/certiorem/hub/DeltaFeedInfoCache.java
./rome-certiorem/src/main/java/com/rometools/certiorem/sub/data/SubscriptionCallback.java

./rome-certiorem/src/test/java/com/rometools/certiorem/hub/DeltaSyndFeedInfoTest.java
./rome-certiorem/src/site/resources/css/site.css
./rome-fetcher/src/main/java/com/rometools/fetcher/FetcherListener.java
./rome-fetcher/src/main/java/com/rometools/fetcher/impl/LinkedHashMapFeedInfoCache.java
./rome-fetcher/src/main/java/com/rometools/fetcher/impl/AbstractFeedFetcherBeanInfo.java
./rome-fetcher/src/main/java/com/rometools/fetcher/FetcherEvent.java
./rome-fetcher/src/test/java/com/rometools/fetcher/impl/HashMapFeedInfoCacheTest.java
./rome-fetcher/src/test/java/com/rometools/fetcher/impl/DiskFeedInfoCacheTest.java
./rome-fetcher/src/site/resources/css/site.css

./rome-modules/src/main/java/com/rometools/modules/thr/ThreadingModule.java
./rome-modules/src/main/java/com/rometools/modules/thr/io/ThreadingModuleParser.java
./rome-modules/src/main/java/com/rometools/modules/thr/io/ThreadingModuleGenerator.java
./rome-modules/src/main/java/com/rometools/modules/thr/ThreadingModuleImpl.java
./rome-modules/src/main/java/com/rometools/modules/atom/io/AtomModuleGenerator.java
./rome-modules/src/main/java/com/rometools/modules/atom/io/AtomLinkAttribute.java
./rome-modules/src/main/java/com/rometools/modules/atom/io/AtomModuleParser.java
./rome-modules/src/main/java/com/rometools/modules/atom/modules/AtomLinkModuleImpl.java
./rome-modules/src/main/java/com/rometools/modules/atom/modules/AtomLinkModule.java
./rome-modules/src/main/java/com/rometools/modules/sse/modules/Sync.java
./rome-modules/src/test/java/com/rometools/modules/yahooweather/io/WeatherGeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/yahooweather/io/WeatherModuleParserTest.java
./rome-modules/src/test/java/com/rometools/modules/AbstractTestCase.java
./rome-modules/src/test/java/com/rometools/modules/photocast/io/GeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/opensearch/OpenSearchModuleTest.java
./rome-modules/src/test/java/com/rometools/modules/thr/io/ThreadingModuleTest.java
./rome-modules/src/test/java/com/rometools/modules/content/ContentModuleParserTest.java
./rome-modules/src/test/java/com/rometools/modules/content/ContentModuleGeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/content/ContentModuleImplTest.java
./rome-modules/src/test/java/com/rometools/modules/content/ContentItemTest.java
./rome-modules/src/test/java/com/rometools/modules/atom/AtomLinkTest.java
./rome-modules/src/test/java/com/rometools/modules/ITunesGeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/mediarss/MediaModuleTest.java
./rome-modules/src/test/java/com/rometools/modules/mediarss/types/TimeTest.java
./rome-modules/src/test/java/com/rometools/modules/mediarss/GoogleTest.java
./rome-modules/src/test/java/com/rometools/modules/sle/GroupAndSortTest.java
./rome-modules/src/test/java/com/rometools/modules/sle/io/ModuleGeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/sle/io/ModuleParserTest.java
./rome-modules/src/test/java/com/rometools/modules/base/io/GoogleBaseGeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/base/io/GoogleBaseParserTest.java
./rome-modules/src/test/java/com/rometools/modules/base/types/FloatUnitTest.java
./rome-modules/src/test/java/com/rometools/modules/base/types/IntUnitTest.java
./rome-modules/src/test/java/com/rometools/modules/sse/SSEParserTest.java
./rome-modules/src/test/java/com/rometools/modules/cc/io/CCModuleGeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/cc/io/ModuleParserTest.java
./rome-modules/src/test/java/com/rometools/modules/cc/types/LicenseTest.java
./rome-modules/src/test/java/com/rometools/modules/itunes/ITunesGeneratorTest.java
./rome-modules/src/test/java/com/rometools/modules/itunes/ITunesParserTest.java
./rome-modules/src/site/resources/css/site.css

./rome-certiorem-webapp/src/main/java/com/rometools/certiorem/webapp/NotifyTest.java
./rome-certiorem-webapp/src/main/java/com/rometools/certiorem/webapp/SubTest.java
./rome-certiorem-webapp/src/main/java/com/rometools/certiorem/webapp/SubServlet.java
./rome-certiorem-webapp/src/main/java/com/rometools/certiorem/webapp/HubServlet.java
./rome-certiorem-webapp/src/main/java/com/rometools/certiorem/webapp/ServerModule.java

Please, add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

These source files 
./rome-modules/src/main/java/com/rometools/modules/base/CustomTagImpl.java
./rome-modules/src/test/java/com/rometools/modules/itunes/types/DurationTest.java
report the old address of GNU Free Software Foundation
59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
can you correct with
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
for Fedora is considered as a bug, see https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address
Thanks in advance
Regards

**Comment by puntogil** [comment]
This file have unknown license:
./rome/src/test/java/com/rometools/rome/unittest/TestDublinCore.java
(c) Mobile IQ Ltd 2009. All Rights Reserved

**Comment by mishako** [comment]
`TestDublinCore.java` was introduced in fb021e8 by @imk. I'm sure he meant it to have the same license as the rest of Rome, but I guess we should wait for him to confirm?

**Comment by imk** [comment]
@mishako sorry it took so long to notice this, the file mentioned above wasn't created by me, it's originating by a patch provided by an unknown user in #125 (#issuecomment-25374450).

**Comment by mishako** [comment]
@imk No problem, thanks for the answer! Well, then my pull request #292 remains being useful.
