### ISSUE TITLE
Get the future date with the date parser when it is not GMT time

### ISSUE THREAD

**Issue by kuncong** [rometools/rome#298]
Hi Experts,

recently I had a issue with the date parsing and it bothering me for a while.

The problem is that for some news feeds I get some future date after parsing. for instance, the news in CBSNews feed is like:
```
<item>
<title>
Young, gay and male: Suicide survey spotlights risks
</title>
<link>
http://www.cbsnews.com/news/young-gay-bisexual-men-may-face-higher-suicide-risk/
</link>
<description>
Gay and bisexual men younger than 26 were much more likely to attempt suicide or harm themselves, report finds
</description>
<pubDate>Wed, 27 Apr 2016 19:25:14 -0400</pubDate>
<image>
http://cbsnews2.cbsistatic.com/hub/i/r/2011/06/06/54843bc9-a644-11e2-a3f0-029118418759/thumbnail/60x60/1a0770efe9827ab646913a389f34f2b8/gayteens_istock.jpg
</image>
<guid isPermaLink="false">00825f56-71ac-4b9c-98ab-8ff9de02153d</guid>
</item>
```
 
I programmatically set my default timezone to be GMT(the default timezone of mime is GMT +8), After the parsing with Rome API and the pubDate is converted to be GMT time which is “Wed Apr 27 23:25:14 GMT 2016”, but my system time in GMT is “Wed Apr 27 23:18:07 GMT 2016”, it is like the time from the news is in the future. I also checked the time in the article from website, it is “April 27, 2016, 4:13 PM”.
 
my question is that is the feed using the correct pubDate for the news? if it is correct time in the feed, how can I parsing it correctly. My news aggregator is running for many different feeds with all kinds of time format, it seems the feeds with no GMT time has this kind of issue.
the same issue for "`<pubDate>Wed, 27 Apr 2016 14:15 EDT</pubDate>`" as well

It is very much appreciated to hear any expertise from you.
 
Thanks in advance.
Best regards
xisheng

**Comment by mishako** [comment]
Hi xisheng,

Although in general dealing with time is hard, your case looks pretty simple to me. You say that at `23:18:07 GMT` they published news with publish time `19:25:14 -0400` (`23:25:14 GMT`). My conclusion would be that their pubDate value is not correct.

**Comment by kuncong** [comment]
Hi Mishako,

Thank  you very much for your reply.  I agree that the time from the news is incorrect. since my newsagrregator are still in the test phase, I didn't running it all the time and the issues I found about it that is randomly. so it is not like that at  3:18:07 GMT they published news with publish time 19:25:14 -0400 (23:25:14 GMT). the news may published already a few hours ago. but anyway, it can't be the time in future. What I guess is that they mixed up they local time with GMT timeoffset. for instance that 19:25:14 -0400, the 19:25:14 is already the GMT time which is correct part and at least it is close to the real article time.
Currently, I had about 200 news feeds undering parsing and a few of them have this kind of problem. What I want to do is to deal with the date parsing case by case based on the feed itself. I want to apply a walk-around on this kind of news, if the date in the future found I will cut off the timeoffset like by replacing 19:25:14 -0400 to be 19:25:14 -0000.

could you give me some suggestion that how should I do it in your opinion, and where do you think it is the best place to do this kind of implementation?

Thanks a lot
best regards,
Xisheng

**Comment by mishako** [comment]
The right thing to do would be to let the owners of those few problematic feeds know about the issue. It's probably an easy fix on their side. Custom workarounds is generally not a good way of dealing with bad data. But as a short-term fix you could do something like this:
```java
class Feed {
  String url;
  Optional<Duration> fix; // Duration.ofHours(-4) for CBS news
}

List<Feed> feeds = getFeeds();

for (Feed feed : feeds) {
  SyndFeed parsed = parseFeed(feed.url);

  if (feed.fix.isPresent()) {
    for (SyndEntry entry : parsed.getEntries()) {
      entry.setPublishedDate(
          new Date(entry.getPublishedDate().getTime() + fix.get().toMillis()));
    }
  }

  // use parsed feed
}
```

**Comment by kuncong** [comment]
Thanks for your suggestions, it is helpful to me.
