### ISSUE TITLE
parsing the image url with the space issue

### ISSUE THREAD

**Issue by kuncong** [rometools/rome#302]
Hi Expert,

I have a issue when parsing the abcNews feed. some urls have spaces inside and lead to the exception below:
2016-05-10 02:51:04 [Thread-19] - Exception parsing thumbnail tag.
java.net.URISyntaxException: Illegal character in path at index 49: http://a.abcnews.com/images/International/Alberta Fire material-0D503.mov_4x3t_144.jpg
    at java.net.URI$Parser.fail(URI.java:2848)
    at java.net.URI$Parser.checkChars(URI.java:3021)
    at java.net.URI$Parser.parseHierarchical(URI.java:3105)
    at java.net.URI$Parser.parse(URI.java:3053)
    at java.net.URI.<init>(URI.java:588)

Is there a way to fix this problem?

Thanks
http://feeds.abcnews.com/abcnews/internationalheadlines

**Comment by mishako** [comment]
Spaces are not allowed in URL. See [RFC 3986](http://tools.ietf.org/html/rfc3986) (or http://stackoverflow.com/questions/497908 if you prefer simple answers).

Of course Rome could be lenient and replace spaces with `%20`. We are already doing it for MRSS (see #253 and corresponding commit 6c676c8), although incorrectly (with a plus sign `+` instead of `%20`). What do you think? @kuncong @PatrickGotthard

**Comment by kuncong** [comment]
Hi Mishako,

Thanks a lot for the reply, I do include the romeModules lib 1.6.0, but it seems I still have the issue. do I need some special configuration to use the right parser for the urls with spaces?

**Comment by mishako** [comment]
@kuncong The commit I mentioned doesn't cover your case. Rome doesn't fix spaces in every URL. And when it does, it does it incorrectly anyway. So you have two options:
 1. Tell Abc news to fix their feed
 2. Make Rome always fix spaces

**Comment by PatrickGotthard** [comment]
I think we should replace spaces in URLs with %20

**Comment by PatrickGotthard** [comment]
I've added a utility class with a convenience method for fixing such "common" problems and applied this method to the MediaModuleParser class to fix the wrong space replacement mentioned above.

I will not apply this URI fix to every single spot in the code - I will only apply it when a user creates an issue for that. The feed mentioned above does not have the problem anymore (at least not now) and I have no idea where the mentioned exception was thrown (incomplete stacktrace) - so I will close this issue for now.
