### ISSUE TITLE
Support for auto discovery

### ISSUE THREAD

**Issue by mcramm** [rometools/rome#305]
Does ROME have any support for feed auto-discovery? I've tried looking through the documentation but can't determine if it does or not.

**Comment by PatrickGotthard** [comment]
Hi @mcramm,

ROME doesn't have any auto-discovery mechanism. But I wonder what you mean with feed auto-discovery?

Regards,
Patrick

**Comment by mcramm** [comment]
I was referring to a wish list I found here: https://rometools.github.io/rome/Fetcher/WishList.html, but I wasn't sure if it was abandoned or not.

The mechanic here would be looking for link tags like:

```html
<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="the-feed-url">
```
on the body of a page. Working around this issue without ROME isn't a terribly hard problem, I just wanted to make sure I'm not doing any extra work I don't need to :D.

**Comment by PatrickGotthard** [comment]
I think it's an interesting feature. Would you like to implement this and create a pull request?

**Comment by mishako** [comment]
Closing this issue because the question has been answered.
