### ISSUE TITLE
Unable to get pubDate from Rss 2.0 Feed

### ISSUE THREAD

**Issue by Vipulpal** [rometools/rome#313]
Using ROME version 1.6.0 and 
feed in reference here is _http://in.investing.com/rss/market_overview.rss_
For this feed, SyndFeed's getPublishedDate() is returning null

On further exploration I found pubDate format (<pubDate>Jul 20, 2016 04:40 GMT</pubDate>)
is not as per RFC 822 and to support this we have an option to define custom date parser using rome.properties.
I tried with the format
datetime.extra.masks=yyyy-MM-dd'T'HH:mm:ss|MMM d, yyyy'T'HH:mm z
or
datetime.extra.masks=yyyy-MM-dd'T'HH:mm:ss|MMM d, yyyy HH:mm z
but no luck, for checking whether configuration is getting read or not I tried with junk values ;p but didn't get any exception.

Need a help on this issue,

**Comment by mishako** [comment]
@Vipulpal `SyndFeed::getPublishedDate` is for the publish date of the `<channel>` element. There is no `<pubDate>` under the `<channel>` element in your feed. If you want to get publish dates of the `<item>` elements, use `SyndFeed::getEntries` and then `SyndEntry::getPublishedDate`.
