### ISSUE TITLE
No connection timeout/unknown host exception callback when there is no internet

### ISSUE THREAD

**Issue by rohit5ram** [rometools/rome#314]
SyndFeedInput input = new SyndFeedInput();
XmlReader reader = null;
try {
   HttpURLConnection conn = (HttpURLConnection) feedUrl.openConnection();
   conn.setConnectTimeout(3000);
   reader = new XmlReader(conn);
   SyndFeed feed = input.build(reader);
   feed.setFeedType("rss_2.0");
} catch (Exception e) {//handle the exception}

The above piece of code is not resulting in timeout/unknown host exception when there is no internet. The task keeps waiting forever stalling other async tasks in my app.

**Comment by mishako** [comment]
I would guess that it's not caused by Rome. Have you tried doing the same without Rome?
```
HttpURLConnection conn = (HttpURLConnection) feedUrl.openConnection();
conn.setConnectTimeout(3000);
conn.getInputStream().read();
```

**Comment by vishnuganta22** [comment]
Handling the HttpConnection on our own and send the response inputStream of the HttpConnection as a parameter to Rome SyndFeedInput  solved the issue.

OkHttpClient httpClient = new OkHttpClient();
httpClient.setConnectTimeout(3000, TimeUnit.MILLISECONDS);
Request request = new Request.Builder().url(feedUrl).build();
Response response = httpClient.newCall(request).execute();
reader = new XmlReader(response.body().byteStream());

**Comment by mishako** [comment]
I bet `OkHttpClient` client works better because it's not using `HttpURLConnection`. In general I would say `HttpURLConnection` should only be used for basic use cases and Rome should encourage usage of third-party http client libraries. I don't have any research to back up my words though.
