### ISSUE TITLE
Under the creation page feed there is a typo

### ISSUE THREAD

**Issue by nunocruz** [rometools/rome#323]
rome/rome/src/site/apt/RssAndAtOMUtilitiEsROMEV0.5AndAboveTutorialsAndArticles/RssAndAtOMUtilitiEsROMEV0.5TutorialUsingROMEToCreateAndWriteASyndicationFeed.apt 

Then a list for entries is created, entries are created and added to the list. Each entry is set with a title, link, published date and a description. The description for the first entry is plain **test**, for the third entry is HTML. After each entry is created is added to the list.

test should be text

**Comment by PatrickGotthard** [comment]
Thanks @nunocruz --> fixed
