### ISSUE TITLE
SyndFeed cannot hold both Atom icon and logo

### ISSUE THREAD

**Issue by markhobson** [rometools/rome#325]
Atom feeds can have both an _icon_ and a _logo_ whereas `SyndFeed` only has a single _image_.

The conversion rules are currently as follows:

* Atom -> SyndFeed: image = logo || icon
* SyndFeed -> Atom: icon = image

This leads to an asymmetry when an Atom feed has a logo. For RSS this is not a problem as channels only have a single _image_ and is thus bidirectional.

**Comment by markhobson** [comment]
I would propose introducing a new `SyndFeed.icon` bean property that can exclusively hold the Atom icon as a `SyndImage`. Thus the conversion rules would become:

* Atom <-> SyndFeed: image = logo; icon = icon
* RSS <-> SyndFeed: image = image; icon = null

What do you think?

**Comment by mishako** [comment]
Hi Mark! I like your suggestion. Do you have time to implement it?

**Comment by markhobson** [comment]
Hi @mishako, not immediately but I can try to find some time to look at it. I wanted to make sure that the approach was agreed before expending the effort.

**Comment by markhobson** [comment]
Looks like this is done now - thanks! Can the issue be closed?
