### ISSUE TITLE
pubDate omitted when using iTunes-module

### ISSUE THREAD

**Issue by jannesep** [rometools/rome#329]
The pubDate-tag is omitted from the final feed if I'm adding an EntryInformation module to my entry. Without the following code, the pubDate is printed as it should.
```
ArrayList<Module> modules = new ArrayList<>();
EntryInformation e = new EntryInformationImpl();
e.setDuration(new Duration(1000 * i.getDuration()));
e.setExplicit(false);
modules.add(e);
entry.setModules(modules);
```

Am I missing something or could this be a bug? According to Apple documentation the pubDate-tag should be included https://help.apple.com/itc/podcasts_connect/#/itcb54353390

**Comment by mishako** [comment]
The tricky thing about `pubDate` is that it is stored in the default Dublin Core module (`DCModule`), which gets overridden when you call `entry.setModules`. One way to solve this is to instead append `EntryInformation` module to the existing list:
```java
final List<Module> modules = new ArrayList<>(entry.getModules());
modules.add(entryInformationModule);
entry.setModules(modules);
```

**Comment by jannesep** [comment]
Thanks a lot! This solved my problem.
