### ISSUE TITLE
[parser] Media module parser does not follow specifications for the restriction element

### ISSUE THREAD

**Issue by endorphins** [rometools/rome#331]
The media rss specifications state that the "restriction" element that the "type" attribute is optional 

> when using one of the literal values "all" or "none".

However, the media module parser assumes that type is specified and throws a null pointer exception when it is not on [line 436 of com.rometools.modules.mediarss.io.MediaModuleParser](https://github.com/rometools/rome/blob/master/rome-modules/src/main/java/com/rometools/modules/mediarss/io/MediaModuleParser.java#L436).

**Comment by endorphins** [comment]
Is there any way to override the MediaModuleParser myself? I've tried making my own parser using the same URI and adding that class to my rome.properties file, but it still uses MediaModuleParser instead of the one I've made.

**Comment by endorphins** [comment]
It looks the module parse I made is getting overriden by MediaModuleParser from rome-modules because the rome.properties file from rome-modules gets read after the rome.properties file from my project. Is there an easy way to correct this issue?

**Comment by mishako** [comment]
Thanks for raising the issue! I'm not sure how `rome.properties` overrides work, but I would assume that there is no way to fix it if it doesn't work. But let's then fix the `MediaModuleParser`! Do you feel like writing a patch for making the `type` optional?

**Comment by endorphins** [comment]
Sure I can do that. It looks like the Restriction object already does the optional check in the constructor, so only the parser should need to be updated.

**Comment by endorphins** [comment]
Made a pull request [here](https://github.com/rometools/rome/pull/333) with the fix and an additional test case for it.

**Comment by endorphins** [comment]
Now that this issue has been fixed in version 1.7.3, will that be deployed to maven central?

**Comment by mishako** [comment]
Automatic deployment doesn't seem to work, I will ask @PatrickGotthard to do something about it.

**Comment by mishako** [comment]
@endorphins It's in maven central now! Automatic deployment is not working, I have to ask Patrick to manually deploy it for every new version.

**Comment by endorphins** [comment]
Great! This has fixed my issue and can be closed. Thank you!
