### ISSUE TITLE
Doesn't appear that SyndEntry supports the <id> element for ATOM format.

### ISSUE THREAD

**Issue by jspyeatt** [rometools/rome#332]
If I'm reading the spec correctly the <entry> element should have a `<id>` element within it. I don't see SyndEntry having a getId() or setId() method.

**Comment by mishako** [comment]
Hello! Apparently we have an [explanation](http://rometools.github.io/rome/RssAndAtOMUtilitiEsROMEV0.5AndAboveTutorialsAndArticles/FeedAndEntryURIMappingHowSyndFeedAndSyndEntryUriPropertiesMapToRSSAndAtomElements.html) for it on the website. Wouldn't expect anyone to be able to find it though, so no worries. Basically `<id>` corresponds to `getUri()/setUri()`.
