### ISSUE TITLE
Custom Module is not Loaded by the PluginManager

### ISSUE THREAD

**Issue by bdurepo1** [rometools/rome#334]
I have banged my head for awhile on this. I have defined custom modules for parsing an ATOM feed and added the classes to the rome.properties file, but modules are not mapped to the entries after I call feed.getEntries(). 

I am looking for a checklist that I can use to determine why the classloader does not find my parser. Im using Intellij.

**Comment by mishako** [comment]
Hi Brandon! Thanks for submitting the issue. In general, when asking this kind of questions, it's always better to attach examples of your code. Otherwise it's hard to tell if you're doing something wrong.

Is this how you do it?
```
rss_2.0.item.ModuleParser.classes=com.yourpackage.YourModule
```
```java
SyndEntry entry = ...
Module maybeYourModule = entry.getModule(YourModule.NAMESPACE);
if (maybeYourModule != null) {
  YourModule yourModule = (YourModule) maybeYourModule;
  ...
```

**Comment by mishako** [comment]
I will close this. Let me know if you still have questions.
