### ISSUE TITLE
Support For JSON Feed

### ISSUE THREAD

**Issue by dotquam** [rometools/rome#336]
Any plans to support https://jsonfeed.org/ format?

**Comment by PatrickGotthard** [comment]
Hi @dotquam,

no, we currently won't support JSON Feed for the following reasons:

- ROME concentrates on RSS and Atom
- JSON Feed is still an unknown format
- adding support for JSON feed would add some complexity to the project

Also I think that the developers of JSON Feed should provide libraries for some programming languages by themself when they want to gain some reach.

Regards,
Patrick

**Comment by mishako** [comment]
Just want to add that this initiative is very interesting and exciting (finally something is happening in syndication world). Also it would be a good test of Rome's extensibility. Let's wait a bit and see where the trend goes.

**Comment by fschiettecatte** [comment]
I would like to re-raise this question, seems like JSON feeds are getting some traction, any thoughts?
