### ISSUE TITLE
RSS GUID's isPermaLink default is incorrectly set to false

### ISSUE THREAD

**Issue by johnedo1234** [rometools/rome#338]
According to https://www.w3schools.com/xml/rss_tag_guid.asp the default value for a guid's isPermaLink attribute is true.

But in Rome's Guid.java the default is actually false.

If you read a feed with items that don't specify isPermaLink and then write it back out again with Rome, you'll see each guid explicitly written with isPermaLink=false.

**Comment by mishako** [comment]
Hello and thanks for submitting the issue! I agree with you that Rome should write semantically identical feed to what's been read. I don't know if it's mentioned anywhere in documentation, but I think it's a good property of a parser.

Do you have time to write and submit a fix for this issue?

**Comment by fschiettecatte** [comment]
I'd like to see this bug fixed, it has been in there from the very beginning. What is the process for submitting a fix? Should I fork the code, fix and submit a pull request?

**Comment by mishako** [comment]
@fschiettecatte Yes, the normal github process: https://help.github.com/articles/fork-a-repo/

**Comment by fschiettecatte** [comment]
Done, here is the pull request: https://github.com/rometools/rome/pull/339

**Comment by mishako** [comment]
I merged the PR. I will try to release a new version. We've had problems with releasing in the past, so it might take some time. I will update the issue when it's done.

**Comment by mishako** [comment]
I asked @PatrickGotthard to promote the release to Maven Central. He hasn't answered yet.

**Comment by fschiettecatte** [comment]
@mishako No problem, was not expecting it to be pushed out right away

**Comment by PatrickGotthard** [comment]
Hi,

sorry for the late response, I was very busy the last days. Version 1.7.4 will be available on Maven Central soon :)

Regards,
Patrick
