### ISSUE TITLE
Multiple Request Parameters in link field ampersand is encoded wrong

### ISSUE THREAD

**Issue by The-Crocop** [rometools/rome#343]
I am using AbstractRssFeedView. Inside the buildFeedItems method I am doing:

`item.setLink("http://sampleurl.com?a=5&b=3")`
when my rss is rendered the second parameter is encoded wrong as &amp;
turning into:
`<link>http://sampleurl.com?a=5&amp;b=3</link>`  in the rendered rss
which makes the link unusable

**Comment by imk** [comment]
But that's the correct way to encode `&` in XML. A literal `&` isn't allowed in XML, it must be written as `&amp;` or must be enclosed in a `CDATA` section.
