### ISSUE TITLE
Parsing error with baidu rss

### ISSUE THREAD

**Issue by herau** [rometools/rome#346]
Hello, 

i have an error during parsing a baidu rss feed:

```java
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.

	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:198)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
```
I've created a github project to reproduce this issue https://github.com/herau/rome-baidu.

Thanks

**Comment by imk** [comment]
I've created a pull request for your example, baidu seems to analyse some headers and is sending a favicon instead of the feed if it doesn't like some headers. So the thrown exception is fine because Rome can't parse the image it's getting in the response instead of the requested feed.

**Comment by herau** [comment]
thanks @imk, i've created a new one because i have now parsing issue with this feed.
#347
