### ISSUE TITLE
Parsing issue of Baidu Feed 

### ISSUE THREAD

**Issue by herau** [rometools/rome#347]
I'm trying to parse a [baidu feed](http://news.baidu.com/ns?cl=2&rn=20&tn=newsrss&word=football) with ROME and i have parsing issue:

- the published date of feed entries are not available 
- I have randomly some � characters in feed entry title / description 

i have a sample project with Junit test in https://github.com/herau/rome-baidu

**Comment by imk** [comment]
I'll have a look again later today.

**Comment by herau** [comment]
@imk sample of date value `Sat, 22 Jul 2017 15:55:00`, looks like not match any RFC822 mask during the parsing. 
Regarding the closest matching mask, `EEE, dd MMM yy HH:mm:ss z`, the date not contains the TIME ZONE value and the year is set to four characters instead of two

**Comment by imk** [comment]
@herau about the date format, you could try to define custom date formats for rome like described in http://rometools.github.io/rome/RssAndAtOMUtiliEsROMEV0.7DateAndTimeParsing.html, so putting a `rome.properties` in `src/main/resources` with something like

`datetime.extra.masks=EEE, dd MMM yyyy HH:mm:ss`

should do the trick about the pub date. But I couldn't validate that yet, not on my dev pc at the moment.

**Comment by imk** [comment]
I could finally test the datetime pattern and the charset problems, the mentioned `datetime.extra.masks` is working for me, can you validate that too?

I couldn't reproduce the charset problem, when executing the test, the output I'm getting is added to a [gist](https://gist.github.com/imk/a5860bf41c6dd5720d6918c71a0fd460), maybe a problem with your console charset not supporting all those chinese symbols? But maybe it's a problem with some single chars not in the feed at the moment.

**Comment by herau** [comment]
@imk thanks a lot for the `datetime.extra.masks` tips.

I will test again the rss feed and i will close the issue if i can't reproduce

**Comment by imk** [comment]
@herau you're welcome. If you can reproduce the problem again, could you save and attach the source feed with the misbehaving characters inside, so we can test with the same version of the feed?

**Comment by herau** [comment]
@imk it was my json serializer which is set to UTF-8 by default... My bad. 

Thanks again for your help @imk
