### ISSUE TITLE
Enhance API to expose foreign attributes

### ISSUE THREAD

**Issue by jimsteel** [rometools/rome#351]
My project requires the use of foreign xml attributes on link elements within an atom feed. As far as I can tell, this is perfectly legal in ATOM, but the attributes aren't exposed for reading or writing by the rome API at present.

(pull request to follow)

**Comment by imk** [comment]
Hi @jimsteel,

it is perfectly legal to have foreign attributes on the link element, in its definition on https://tools.ietf.org/html/rfc4287#page-21, there is explicitely `undefinedContent` allowed, `undefinedContent` includes foreign attributes. So extending Rome to support foreign attributes is a great idea, I'm just unsure about the right way to do so. I think that should be discussed what's the best way to implement foreign attributes.

**Comment by jimsteel** [comment]
As much as possible my pull request follows the style of foreign markup (elements) on Entries.

**Comment by imk** [comment]
Yeah, that's right and it's a valid workaround. I'm just thinking that, when a workaround is applied to multiple places, it might be a good idea to think about a cleaner solution. Personally, I don't like to expose internal implementation details like JDom-Elements and -Attributes in the API, I think those details should be covered by the API und just exposed to parsers and generators. But it's more important to get the opinion of the people more involved than me like @PatrickGotthard and @mishako.

**Comment by mishako** [comment]
It's unfortunate that we have to expose Jdom types. I think the proper way to do this would be to create an abstraction on top of `org.jdom2.Attribute` and pass it around instead.

**Comment by imk** [comment]
I'll try to make a proposal for an extension to enable the required functionality while keeping jdom internal. But it'll take some more days.

**Comment by jimsteel** [comment]
I'm a bit skeptical of the need for this, to be honest. At the end of the day, this content is foreign, so by definition outside the scope of rome's API. I'm not sure I see the harm in encapsulating foreign elements in a foreign API.

Regardless of that, given that it affects already existing functionality (foreign elements) in the same way as the pull request, it may be a separate issue to this specific ticket.

**Comment by imk** [comment]
Those foreign alements are comparable to feed or entry modules, these are foreign elements to the base feed too. Those modulea aren't exposed as xml elements and so these attributes shouldn't be exposed by the API.

**Comment by mishako** [comment]
I will close this issue and the corresponding PR, because it's been more than two months without any progress. If anyone has a good idea on how to proceed with this - let me know and I will reopen the issue. Anyway I think it's a valid use-case and something we should prepare for in Rome 2.
