### ISSUE TITLE
Styelsheet not rendered 

### ISSUE THREAD

**Issue by The-Crocop** [rometools/rome#359]
I use AbstractRss View.
when I do channel.setStylesheet("style.xsl") it is not rendered in the final rss output.
Any settings I forgot oris it simply not possible?

**Comment by imk** [comment]
@The-Crocop Could you provide some sample code?

**Comment by mishako** [comment]
Closing the issue due to no updates for 2 months.

**Comment by parthbulusu** [comment]
This is still an issue 
		`channel.setStyleSheet("style.xsl");`
Should have following in output rss
                `<?xml-stylesheet type='text/xsl' href='style.xsl'?>`
