### ISSUE TITLE
GoogleBaseGenerator Namespace prefix is different from google  

### ISSUE THREAD

**Issue by gokhanakgul** [rometools/rome#361]
Hi 
I am trying to generate Google merchant rss xml file with Rome 's GoogleBaseGenerator.
i realized that exported xml's namespace field different what google describe in following web page 
https://support.google.com/merchants/answer/160589?hl=en

As far as i understood that it is not possible to change it programaticaly. How can i change the namespace prefix as google describes ? 

Best regards

**Comment by imk** [comment]
Hi @gokhanakgul 

I don't think there's a need to customize the namespaces prefix. The prefix for namespaces in XML is comparable to a variable referencing the namespace URI. Wehn working with XML libs, you generally don't tell the lib "look for an element `g:image_link`" but instead "look for an element `image_link` with namespace URI `http://base.google.com/ns/1.0`. So no need to customize the prefix.

If you're forced to work with some real broken XML parsers (that don't parse XML but use something like regex to try to read the content) and so you should really be forced to define the prefix, you could use one of `SyndFeedOutput` method that generate a W3C Dom or a Jdom Document and xou could try to change the namespace prefix there.

**Comment by gokhanakgul** [comment]
Thanks for you feedback. I checked the produced xml by GoogeBaseGenerator , it seems outdated ,there are many missing Module in the library .

**Comment by imk** [comment]
I've created a new issue for the missing elements, see #362 - I've just checked some random elements and could see there are some elements not supported yet. If you're allready having a list of required elements (and their types), that would be helpful.
