### ISSUE TITLE
Media RSS price tag uses Double for the price amount

### ISSUE THREAD

**Issue by vsavicks** [rometools/rome#372]
Using _double_ type for monetary values can cause rounding error in arithmetic operations, hence a more suitable type is recommended, such an _integer_, _long_ or _java.math.BigDecimal_.

**Comment by snursmumrik** [comment]
A fix based on the _java.math.BigDecimal_ and _java.util.Currency_ is implemented in the pull request #371.

The recently accepted pull request #369 along with the pull request #371 should also close the issue #190 about the incomplete **Media RSS** support.
