### ISSUE TITLE
Generate <Media:Content> with SyndFeed or RSS

### ISSUE THREAD

**Issue by keyuls** [rometools/rome#373]
Is there a way to generate <Media:Content> with SyndFeed or RSS?

I am following [MediaRSS example](https://rometools.github.io/rome/Modules/MediaRSS.html) to create media content. But with Rome version 1.9.0 (maven) `MediaContent` is not defined.

**Comment by mishako** [comment]
8 months passed, but better answer later than never.
`MediaContent` lives in `rome-modules`. You need to add `rome-modules` to your dependencies in addition to `rome`.
