### ISSUE TITLE
Published date is null after parsing

### ISSUE THREAD

**Issue by mjremijan** [rometools/rome#378]
I've run into a parsing problem where the published date is null.  The RSS feed sets the `<pubDate>` tag like this:

`<pubDate><![CDATA[Tue, Jan 23 2018 02:54:55 MST]]></pubDate>`

When Rome parses this RSS feed, `SyndEntry.getPublishedDate()` returns null.  Is it because the value of the date is wrapped in a `<![CDATA[  ]]>` ?  Any way I can get this date?

Attached is the RSS file I'm attempting to parse.

[java_ranch_ejb.xml.txt](https://github.com/rometools/rome/files/1660741/java_ranch_ejb.xml.txt)

**Comment by mjremijan** [comment]
I have some additional information on this.  The format for the date that is being used  by this RSS feed - `Tue, Jan 23 2018 02:54:55 MST` doesn't match the date parsing util in Rome.  I'm assuming this feed is not formatting it's date per RSS standards.  If I switch the `Jan` and `23` parts so it matches standards `Tue, 23 Jan  2018 02:54:55 MST` then Rome parses the date fine.

**Comment by Tommy-Geenexus** [comment]
@mjremijan 
`<pubDate>` must match RFC 822 (with the exception being that the year may be expressed in 4 characters).

The scheme looks as follows:
`EEE, dd MMM yy(yy) HH:mm:ss Z`

As you can see the day must precede the month.
This means the feed is not valid RSS, and ROME correctly returns a null value.

**Comment by mishako** [comment]
Expected behavior then. Closing this, although we can still look into being even more lenient in the next versions.
