### ISSUE TITLE
SyndEntry.getAuthors empty for RSS feeds with dc:creator

### ISSUE THREAD

**Issue by zsau** [rometools/rome#380]
The Javadoc for `SyndEntry.getAuthors` says:
```
For Atom feeds, this returns the authors as a list of SyndPerson objects, for RSS feeds this method is a convenience method, it maps to the Dublin Core module creator.
```
However, on a SyndEntry created from an RSS feed whose items use `dc:creator`, `.getAuthors` returns an empty list, while `.getAuthor` (without the `s`) does return the content of `dc:creator`. So I think either the docs or the implementation of `.getAuthors` is wrong here.

**Comment by mishako** [comment]
I fixed the docs. Can't fix the implementation because of backward compatibility. Same for #381
