### ISSUE TITLE
Incorrect RSS version throws IllegalArgumentException

### ISSUE THREAD

**Issue by gferry** [rometools/rome#387]
Hi,

I tried to handle the following RSS feed with Rome (versions tested : 1.5.1, 1.9.0)
[https://www.lemagit.fr/rss/ContentSyndication.xml](https://www.lemagit.fr/rss/ContentSyndication.xml)

RSS version mentioned in this document is 2.2 (which is incorrect, it should be 2.0).
While loading the URL, I get the following issue :
```
java.lang.IllegalArgumentException: Invalid document                                                                                                                                       
      at com.rometools.rome.io.WireFeedInput.build
```
It seems Rome cannot allocate an adequate parser based on RSS version.
However, if I correct the RSS version in a local copy, served through a local server, it works just fine.

Is there an option somewhere in the API to ignore force RSS version, so it won't be parsed ?

Thanks a lot !

Best regards,
Guillaume.

**Comment by gferry** [comment]
Ok,

Since it's not a Rome issue, I just added a preprocessing step that handles a DOM Document, in which I set a valid RSS version.

Everything works fine !

**Comment by mishako** [comment]
:ok_hand:
