### ISSUE TITLE
XMLReader cannot be loaded in tomcat

### ISSUE THREAD

**Issue by changbaishan** [rometools/rome#388]
Here is a utility code in my servlet.
this.url = url;
		this.name = name;
		SyndFeedInput input = new SyndFeedInput();
		forecasts = new LinkedList<Forecast>();
		try {
			SyndFeedImpl feed = (SyndFeedImpl) input.build(new XmlReader(new URL(url)));
			populate(feed);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

However, Tomcat throws an exception:
java.lang.NoClassDefFoundError: com/rometools/rome/io/XmlReader
	controls.EnvironmentReport.doGet(EnvironmentCanada.java:49)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

I have jdom2 and rome jars included in the referenced libraries. The same code works well in non-servlet situations.

**Comment by PatrickGotthard** [comment]
Hi @changbaishan,

I don't think that we have a general Tomcat/Servlet related problem in Rome. I know many applications that use Rome in a Servlet Container (e.g. spring.io to name a well-known example). Also I'm using Rome my personal feed reader together with Spring Boot 2 (embedded Tomcat).

Please check your classpath first or try to create a minimal example that demonstrates the problem.

Regards,
Patrick
