### ISSUE TITLE
iTunes Spec Update adding optional <itunes:title> tag

### ISSUE THREAD

**Issue by LizzAy** [rometools/rome#389]
You already included the new tags for the iOS 11 feature of serial podcasts. But I really do miss the new tag <itunes:title>. This is a short description:

> <itunes:title> Optional. Title-only override, must not contain season or episode numbers or show name

Do you plan to add this soon?
Thanks for a short feedback and kind regards

**Comment by mishako** [comment]
Not sure why it was not included in #358. Anyway, I added it and released version `1.11.0`. Waiting for it to reach Maven Central.

**Comment by LizzAy** [comment]
Nice! Thanks a lot :+1:
