### ISSUE TITLE
Missing DublinCore properties - RSS 0.91

### ISSUE THREAD

**Issue by gferry** [rometools/rome#390]
Hi,

I'm trying to parse the following RSS feed:
[http://www.gauchemip.org/backend.php3](http://www.gauchemip.org/backend.php3)

This feed contains **date** tags, and also **dc:date** alternatives for each item.
My wild guess is that rome will ignore **date** tags, which seem invalid, and honor **dc:date** tags, which seem valid.

However, my parsed entries does not contain any date.
Is it because this old feed has an invalid syntax ? It is nicely supported in Firefox, for instance.

Thanks a lot,
Regards.

**Comment by gferry** [comment]
I have reproduced this behaviour on version 1.5.1 and 1.9.0, by the way.

**Comment by mishako** [comment]
Hi!

Let me know if I'm wrong, but it looks like modules in RSS were introduced in version 1.0 (i.e. after 0.91), so they can't use `dc:date` in the feed.

Also, there is no `date` tag in RSS. There is a `pubDate` tag, but it was introduced on `item` level only in RSS 0.93.

**Comment by gferry** [comment]
Hi mishako,

Thanks for your reply.
I agree with you, and that's what I meant by _this old feed has an invalid syntax_ ... for its version.

But, anyway, Rome does detect dc namespace even on this very file, but doesn't fill dc properties.
That' no big deal, I'll add some preprocessing steps to extract dc properties in this particular case.

My purpose is to align compatibility with Firefox syndication support : and, the latter does a great job handling this feed (with some hacks, I guess).

Thanks again !

Regards,
G.

**Comment by mishako** [comment]
@gferry 
I see. What if you put a `rome.properties` file on your classpath (e.g. in `src/main/resources`) with this line in it:
```properties
rss_0.91U.item.ModuleParser.classes=com.rometools.rome.io.impl.DCModuleParser
```
This will force Rome to run DC parser even for this old version of RSS.

**Comment by gferry** [comment]
Awesome !
It works like it a charm, thanks a lot :)

**Comment by gferry** [comment]
Issue closed.
