### ISSUE TITLE
XML External Entity (XXE) Vulnerability

### ISSUE THREAD

**Issue by Nadahar** [rometools/rome#392]
It seems to me that rometools is vulnerable to [XML External Entity (XXE) Processing](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing) through the use of `org.xml.sax.XMLReader`. I haven't checked if other vulnerable XML parsers are used as well, but I found "unprotected" calls to `XMLReader` while searching for instances in our own code, since rometools is one of our dependencies.

It should be fairly easy to fix unless external entities are actually needed. In most cases they are not, so they can just be [turned off](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#XMLReader).

**Comment by mishako** [comment]
@Nadahar Hi! Thanks for the report! Could you please show where you found unprotected calls to `XMLReader`? We seem to already have the fix recommended by OWASP in place:
https://github.com/rometools/rome/blob/master/rome/src/main/java/com/rometools/rome/io/WireFeedInput.java#L349

**Comment by Nadahar** [comment]
@mishako Hi, and thank you for your reply. 

It seems I didn't check your code thoroughly enough. In my defense I did go through a lot of code, both our own and our dependencies looking for this, so I might have had a little short-circuit.

I don't remember exactly how I came to the conclusion now, but I think it was this: https://github.com/rometools/rome/blob/95427fb2ae6bfbed06dad5ff4383bfe1d1bb170a/rome/src/main/java/com/rometools/rome/io/SAXBuilder.java#L52

I see now that it's not really a problem because you impose the restrictions after you're creating the parser. I just saw that the ```com.rometools.rome.io.SAXBuilder``` itself isn't "protected" so that you have to manually "protect" all parsers created with it. It is possible to set the features for the [builder itself](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#SAXBuilder), which is what I guess I was expecting/looking for.

Even though ```com.rometools.rome.io.SAXBuilder``` is public and can be used by anyone to create an "unprotected" parser, it's no different than ```org.jdom2.input.SAXBuilder``` in that sense.
