### ISSUE TITLE
itunes:block tag is not self closing

### ISSUE THREAD

**Issue by LizzAy** [rometools/rome#393]
If the block tag is set we get something like this in our feed:
`<itunes:block />`
As I've read in various discussions with the Apple Support, this is not correct. The block tag is not self closing and needs to look like this ('yes' is case sensitive here.):
`<itunes:block>yes</itunes:block>`

Could you fix this?

**Comment by mishako** [comment]
@LizzAy Thanks for raising the issue!

Looks like it's `Yes` not `yes`?
> Specifying the <itunes:block> tag with a Yes value at the channel level (podcast), prevents the entire podcast from appearing in Apple Podcasts.

https://help.apple.com/itc/podcasts_connect/#/itcb54353390
