### ISSUE TITLE
Broken link in javadoc

### ISSUE THREAD

**Issue by yaroslavm** [rometools/rome#397]
Link http://diveintomark.org/archives/2004/02/13/xml-media-types in `/rome/src/main/java/com/rometools/rome/io/XmlReader.java` is broken and domain is free to purchase. So it seems better to remove this link or change it to something like [https://rometools.github.io/rome/RssAndAtOMUtilitiEsROMEV0.5AndAboveTutorialsAndArticles/XMLCharsetEncodingDetectionHowRssAndAtOMUtilitiEsROMEHelpsGettingTheRightCharsetEncoding.html](url)

**Comment by mishako** [comment]
I agree!
