### ISSUE TITLE
How to extract extra entry data?

### ISSUE THREAD

**Issue by atbest** [rometools/rome#406]
For example, I want to extract `prism:section`, `prism:startingPage` and `prism:endingPage` from the test file https://github.com/rometools/rome/blob/master/rome/src/test/resources/rss_1.0-ns-on-channel.xml . I cannot find a method to extract these data using rome. Thanks.

**Comment by mishako** [comment]
@atbest Sorry for late answer! I'm afraid you would need to implement a module for Rome to be able to extract prism elements. I don't see any mentions of `prism` in the existing code. Creating a new module is not exactly straightforward, but here is an example: https://github.com/rometools/rome/pull/417 (I haven't reviewed it yet though).
