### ISSUE TITLE
Impossible to delete media entry (atom)

### ISSUE THREAD

**Issue by mr-rycho** [rometools/rome#407]
It is impossible to delete a media entry with atom's `FileBasedCollection.deleteEntry` because media entries have ids that are uris (i.e. "_http://[host]....._") (assigned in `FileBasedCollection.updateMediaEntryAppLinks` : `entry.setId(getEntryMediaViewURI(fileName))` ) but while deleting `FileBasedCollection.updateFeedDocumentRemovingEntry` looks for ids that start with the string "`urn:uuid:`". (rome propono 1.12.0)

**Comment by mishako** [comment]
@mr-rycho Hi! Unfortunately propono module is deprecated and this issue is unlikely to receive enough attention to get fixed. Hope it's not a big issue for you. Or maybe you can look into fixing it yourself?

**Comment by PatrickGotthard** [comment]
As mishako already mentioned, rome-propono is deprecated and will be removed soon.
