### ISSUE TITLE
Question: embed media:thumnails in atom:link

### ISSUE THREAD

**Issue by thisismana** [rometools/rome#413]
The [specs for the MSN news](https://partnerhub.msn.com/docs/spec/vcurrent/inline-related-links/AAsCr) state that related content for entry MUST contain a `<media:thumbnail>`

```<item>
<…>
  <!-- Example of specifying 3 Related Links. In RSS, you need to use of the atom namespace `xmlns:atom="http://www.w3.org/2005/Atom"` -->
  
  <!-- REQUIRED: links must have valid "href" and "title" attribute values.-->
  <atom:link rel="related" type="text/html" href="https://contoso.com/news_1.html" 
      title="New IRS proposal">
    
    <!-- REQUIRED: you must provide a thumbnail image with the link -->
    <media:thumbnail url="https://contoso.com/image2.jpg"  /> 
  </atom:link>
```

but the current implementation of the `SyndLink`/`SyndLinkImpl` doesn't allow doing that. Also, the [specification](https://tools.ietf.org/html/rfc4287#section-4.2.7) for `atom:link` does not mention an embedded thumbnail for links.

I currently worked around this by using `Entry#setForeignMarkup()` and write the custom element by hand.

I'd be glad to create a PR to allow doing this with ROME. Questions are: 
* Should it be implemented at all?
* If "yes": What would be the preferred way to do it? (core-lib / module). It kinda depends on the media-rss module since `<media:thumbnail>` must be used.

**Comment by mishako** [comment]
@thisismana Hi! Thank you for a well-written issue and sorry for late response. I think this is a good use case for `Entry#setForeignMarkup()` given that it doesn't match the specifications. There will always be someone doing custom things. I think we shouldn't try to support everything.
