### ISSUE TITLE
Module is not executed although added to rome.properties

### ISSUE THREAD

**Issue by mpgirro** [rometools/rome#421]
I am currently developing a new ROME module for the Bitlove namespace `http://bitlove.org`. You can find the current state [here](https://github.com/mpgirro/rome/tree/bitlove/rome-modules/src/main/java/com/rometools/modules/bitlove).

I am experiencing an issue with the execution of this module. The unit tests fail, and although I've added the Generator and Parser classes to `rome.properties`, the debugger tells me that the respective `generate` and `parse` methods are never called. 

I am a bit lost here, since this module is following the same structure as the other modules I've contributed so far, and these work without any issue.

Does anybody have suggestions why this ROME module does not get executed although it is added to the properties?

Thanks!

**Comment by mishako** [comment]
Sorry, don't have any good ideas. I would suggest enabling the debugger and diving deep into `PluginManager` class (at least that's where I think the magic happens). You should be able to see why your module is not being picked up.

**Comment by mishako** [comment]
@mpgirro Have you managed to figure it out?

**Comment by mpgirro** [comment]
Unfortunately I have not. I think the issue is based on the fact that the module does not attempt to read/write elements for a new namespace. Instead, it tries to read/write only attributes of elements from the standard namespaces (i.e. the `<enclosure>` of RSS 2.0 or the `<link>` of Atom with `rel="enclosure"`). These attributes then have the new namespace. Somehow, ROME does not call the module on the desired elements though, because they do not have the defined namespaces I guess.

I've tried to set the URI of the module to `null` (in the hopes that the modules will then be called on all elements of RSS/Atom), and check for namespace matching on the attributes manually. But the module is still not being called.

**Comment by PatrickGotthard** [comment]
Mey this be related to #351? 
Do you just want to create or parse some foreign attributes?
