### ISSUE TITLE
JIT compiler: "hot method too big"

### ISSUE THREAD

**Issue by ghost** [rometools/rome#422]
The method `XmlFixerReader.read` is hot when many feeds with many items are parsed.

https://github.com/rometools/rome/blob/5fcf0b1a9a6cdedbe253a45ad9468c54a0f97010/rome/src/main/java/com/rometools/rome/io/impl/XmlFixerReader.java#L179

Let the JVM run with the flags

```
-XX:+PrintCompilation -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining
```

and search for the output

```
com.rometools.rome.io.impl.XmlFixerReader::read (763 bytes)   hot method too big
```

We would help the JIT if the granularity of this method was improved.

What do you think?

**Comment by mishako** [comment]
@lutzhorn Nice finding! Unfortunately I don't have much time to work on this. I'm actually focusing on [Rome 2](https://github.com/rometools/rome2) right now. But maybe someone else can look into this issue. Doesn't seem to be critical, but can be interesting to work on.

**Comment by PatrickGotthard** [comment]
I've just looked at the method - it's an unreadable mess and I'm afraid to break it up into smaller methods, but I will try my best :D

**Comment by PatrickGotthard** [comment]
I'm not able to refactor the code without taking too much time.
Also the compiler JIT prints the same warning even for JDK internal methods.
I'll close the issue for now - please file a new issue when it's still relevant.
