### ISSUE TITLE
Can't parse pubDate in RSS for the format yyyyMMdd 20190219

### ISSUE THREAD

**Issue by barrouh** [rometools/rome#423]
Dear Team,
I'm trying to parse the date from format yyyyMMdd for pubDate.
I'm getting the wrong result: Fri Jan 01 01:00:00 CET **20190219**
Below the code example:
**i'm using rome 1.12.0.**
` System.out.println(DateParser.parseDate("20190219",Locale.ENGLISH));`
**rome.properties:**
`datetime.extra.masks=yyyyMMdd`
I think the problem in: 
```
public static Date parseDate(final String sDate, final Locale locale) {
        Date date = parseW3CDateTime(sDate, locale);
        if (date == null) {
            date = parseRFC822(sDate, locale);
            if (date == null && ADDITIONAL_MASKS.length > 0) {
                date = parseUsingMask(ADDITIONAL_MASKS, sDate, locale);
            }
        }
        return date;
    }
```
 `parseUsingMask(ADDITIONAL_MASKS, sDate, locale);` should be called first when the `ADDITIONAL_MASKS` is not empty.
Could you please let me know if I'm implementing something wrong or there is a bug?
Thank you in advance.
Best Regards.

**Comment by lutzhorn** [comment]
`parseW3CDateTime(String, Locale)`, which comes first, parses this input as `yyyy`. I agree that the mask should come first.
