### ISSUE TITLE
SetStylesheet  has no effect

### ISSUE THREAD

**Issue by parthbulusu** [rometools/rome#424]
This is still an issue
`channel.setStyleSheet("style.xsl");`
Should have following in output rss
`<?xml-stylesheet type='text/xsl' href='style.xsl'?>`

**Comment by mishako** [comment]
I guess this feature has never been implemented. At least I can't find any corresponding code. Hopefully someone can implement it if it's not too hard.

**Comment by PatrickGotthard** [comment]
Possible solution: https://stackoverflow.com/questions/17245968/how-to-apply-xml-stylesheet-to-jdom2-document
