### ISSUE TITLE
Impossible to get an empty guid when parsing RSS Feed

### ISSUE THREAD

**Issue by filaruina** [rometools/rome#426]
Hi, by default Rome seems to return the value of <link> tag in case <guid> is missing.
I see this is documented here https://rometools.github.io/rome/RssAndAtOMUtilitiEsROMEV0.5AndAboveTutorialsAndArticles/FeedAndEntryURIMappingHowSyndFeedAndSyndEntryUriPropertiesMapToRSSAndAtomElements.html

Are there any concerns to adding guid field (with `getGuid` and `setGuid`) in a SyndEntry so we can read whenever there is no <guid> tag in an <item> instead of always using the `getUri` that contains this logic?

**Comment by mishako** [comment]
I guess the only concern is that this field is meaningless for Atom, but I don't mind, as long as it's properly documented in the code.

**Comment by PatrickGotthard** [comment]
Hi @filaruina,

could you provide more detailed informations what you expect?
Some code would be helpful too, I don't really understand the issue.

Regards,
Patrick

**Comment by PatrickGotthard** [comment]
I'm closing the issue due to its age - please let me know when it's still relevant.
