### ISSUE TITLE
pubdate from UTC time format cannot be parsed

### ISSUE THREAD

**Issue by dirk-burkhardt** [rometools/rome#431]
There is currently a problem in parsing feeds where the pubdate entry is in UTC format, as for instance Oracle is providing its news: https://www.oracle.com/corporate/press/rss/rss-pr.xml.

**Comment by lutzhorn** [comment]
What is the problem? What is the expected result, what is the actual result? How do the differ?

**Comment by antoniosanct** [comment]
Hi!

`<pubDate>Fri Apr 03 17:00:00 UTC 2020</pubDate>`

Mask `EEE MMM dd HH:mm:ss z yy` is not included as a valid RFC 822 parseable mask @ DateParser's ROME class. Is it really necessary to include it?

Regards!

**Comment by zu1k** [comment]
@antoniosanct really necessary for many rss generators don't follow RFC 822

**Comment by antoniosanct** [comment]
My comment was for ROME maintainers, I don't know if ROME must support RFC 822 standard. In fact, other issue #441 has the same problem.

**Comment by PatrickGotthard** [comment]
Hi @antoniosanct,

we only support standards-compliant masks. If you want to support additional masks, you have to create a rome.properties file in the root of your classpath (e.g. <project>/src/main/resources/rome.properties) with the following content:

```
datetime.extra.masks=EEE MMM dd HH:mm:ss z yy|mask2|mask3
```

Regards,
Patrick

**Comment by antoniosanct** [comment]
Hi! Reading #431 again, I understood wrong. I know extra date masks @ rome.properties file. In fact, it isn't the same issue in #441 fixed. Discard this issue is the best option. Regards!
