### ISSUE TITLE
Duplicate jar - utils/Alternatives

### ISSUE THREAD

**Issue by lucazin** [rometools/rome#433]
Hello!

I have this problem and i try everything to fix without sucess.

When i create the package APK i have a message that alternatives in rome/utils is duplicated.

My version is 1.12.1

Can someone help me ?

Thanks!

**Comment by lucazin** [comment]
![image](https://user-images.githubusercontent.com/28266902/63643762-5558c180-c6ae-11e9-9e19-a0bee8322cf5.png)

**Comment by lucazin** [comment]
Firebase performance plugin.. is correlated with this... i dont know why...im stucked with this issue.. i cant build my project..but i need rome and firebase.

**Comment by PatrickGotthard** [comment]
Sorry, without some sourcecode we are not able to help you.
It seems to be a ProGuard issue: https://stackoverflow.com/questions/33047806/proguard-duplicate-definition-of-library-class

Maybe you are using multiple versions of the rome-utils dependency in your project.

**Comment by lucazin** [comment]
Hello Patrick.
What king source code you need?

implementation 'com.rometools:rome:1.12.1'

and i use this

 dependencies
            {
                classpath 'com.android.tools.build:gradle:3.4.2'
                classpath 'com.google.gms:google-services:4.2.0' // 3.2.0
                classpath 'io.fabric.tools:gradle:1.30.0'
                //classpath 'com.google.firebase:firebase-plugins:2.0.0'
                classpath 'com.google.firebase:perf-plugin:1.3.1'
                classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            }

if i use this i dont have any erros..but my rss feed not work properly

//    implementation files('libs/android-rome-feed-reader-1.0.0.jar')
//    implementation files('libs/jdom-1.1.1-android-fork.jar')


The error is atrelated with firebase performance plugin.

This gradle import implementation 'com.rometools:rome:1.12.1'   create utils jar inside  root jar.

**Comment by lucazin** [comment]
Caused by: java.io.IOException: Can't write [C:\Users\Lucas\Desktop\OnePlaceX\br.com.oneplace\build\intermediates\transforms\proguard\release\0.jar] (Can't read [C:\Users\Lucas\Desktop\OnePlaceX\br.com.oneplace\build\intermediates\transforms\FirebasePerformancePlugin\release\187(;;;;;;;**.class)] (Can't read [com] (Can't read [rometools] (Can't read [utils] (Can't read [Alternatives.class] (Duplicate jar entry [com/rometools/utils/Alternatives.class]))))))

**Comment by lucazin** [comment]
> Sorry, without some sourcecode we are not able to help you.
> It seems to be a ProGuard issue: https://stackoverflow.com/questions/33047806/proguard-duplicate-definition-of-library-class
> 
> Maybe you are using multiple versions of the rome-utils dependency in your project.

Its not proguard i think...because my build broken

**Comment by lucazin** [comment]
![image](https://user-images.githubusercontent.com/28266902/63649549-54a74600-c715-11e9-9ab2-896c45601902.png)

i just have this implementation 'com.rometools:rome:1.12.1'

**Comment by PatrickGotthard** [comment]
Do you use https://code.google.com/archive/p/android-rome-feed-reader/ as a dependency? Maybe that causes the issue.

Sorry, but I do not have enough experience in Android development to help you further.
