### ISSUE TITLE
Packing Issue - Alternatives Rome.Utils / Firebase?

### ISSUE THREAD

**Issue by lucazin** [rometools/rome#434]
Hello.

When i will create APK Signed in AndroidStudio i have a trouble.

* im using this  = implementation 'com.rometools:rome:1.12.1'

* In debug mode its OK, not problem and RSS works fine

* But when i create a signed Package i have a error:

1 º **Duplicate jar entry [com/rometools/utils/Alternatives.class]**

2 º **Caused by: java.lang.RuntimeException: java.io.IOException: Can't write [C:\Users\Lucas\Desktop\OnePlaceX\br.com.oneplace\build\intermediates\transforms\proguard\release\0.jar] (Can't read [C:\Users\Lucas\Desktop\OnePlaceX\br.com.oneplace\build\intermediates\transforms\FirebasePerformancePlugin\release\187(;;;;;;;**.class)] (Can't read [com] (Can't read [rometools] (Can't read [utils] (Can't read [Alternatives.class] (Duplicate jar entry [com/rometools/utils/Alternatives.class]))))))**

3º My proguard: 

**-dontwarn com.rometools.rome.**
-keep class com.rometools.** { *; }
-keep interface com.rometools.** { *; }**

![image](https://user-images.githubusercontent.com/28266902/63649769-56263d80-c718-11e9-81cd-1efb005f5a32.png)

4º Before use this version of rome 1.12.1, i was using this:
**implementation files('libs/android-rome-feed-reader-1.0.0.jar')
implementation files('libs/jdom-1.1.1-android-fork.jar')**

The package build works fine..but my RSS not work properly like version 1.12.1.

Somebody can help me with this problem?  3 days thinking and searching something and nothing.

Other people have the same error, here the link
[https://stackoverflow.com/questions/53854658/duplicate-jar-entry-after-upgrade-to-gradle-3-2-0-3-2-1](url)

**Comment by lucazin** [comment]
I make some tests here and the Signed Build APK Works with version 1.12.1 BUT

1 - ** I have to remove the firebase performance plugin**

2 - What i removed? 
**classpath** 'com.google.firebase:perf-plugin:1.3.1**

**implementation "com.google.firebase:firebaseperf:${FIREBASE_PERFORMANCE_VERSION_SDK_VERSION}**

3º I think have some conflict, but i need use performance firebase plugin and ROME RSS 1.12.1 
What can i do ?


Thanks in advanced!

**Comment by PatrickGotthard** [comment]
Maybe Rome is not working on Android at all. I never tried to use it on Android but there are plenty of artickes on the web, that older versions of jdom are not supported on Android and that even the latest version of jdom has some issues on Android.

**Comment by lucazin** [comment]
So... but i dont understand why the error have some kind of problem with firebase perf plugin .  Now or i use rome or firebase performance..

What you suggest to do?

**Comment by PatrickGotthard** [comment]
Sorry, I can't help. I am not an Android developer. I recommend you to ask your question on StackOverflow.
