### ISSUE TITLE
[RDF] - Namespace collision issue

### ISSUE THREAD

**Issue by gferry** [rometools/rome#437]
Hi there,

Using latest rome version (1.12.1), I'm unable to parse the following RSS feed :
[https://www.enisa.europa.eu/media/press-releases/press-releases/RSS](https://www.enisa.europa.eu/media/press-releases/press-releases/RSS)

I saw a similar issue that has already been closed.

Here's the error stacktrace I obtain while invoking _SyndFeedInput::build_
`org.jdom2.IllegalAddException: The namespace xmlns="http://purl.org/rss/1.0/" could not be added as a namespace to "RDF": The namespace prefix "" collides with the element namespace prefix
        at org.jdom2.Element.addNamespaceDeclaration(Element.java:399) ~[jdom2-2.0.5.jar:2.0.5]
        at org.jdom2.DefaultJDOMFactory.addNamespaceDeclaration(DefaultJDOMFactory.java:323) ~[jdom2-2.0.5.jar:2.0.5]
        at org.jdom2.input.DOMBuilder.buildTree(DOMBuilder.java:320) ~[jdom2-2.0.5.jar:2.0.5]
        at org.jdom2.input.DOMBuilder.buildTree(DOMBuilder.java:252) ~[jdom2-2.0.5.jar:2.0.5]
        at org.jdom2.input.DOMBuilder.build(DOMBuilder.java:141) ~[jdom2-2.0.5.jar:2.0.5]
        at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:287) ~[rome-1.12.1.jar:1.12.1]
`
Best regards,
Guillaume.

**Comment by PatrickGotthard** [comment]
I just tried to reproduce the issue using the following code with the latest version 1.17.0:
```
import java.net.URL;

import com.rometools.rome.feed.synd.SyndFeed;
import com.rometools.rome.io.SyndFeedInput;
import com.rometools.rome.io.XmlReader;

public class TestApplication {

    public static void main(final String[] args) throws Exception {

        final String url = "https://www.enisa.europa.eu/media/press-releases/press-releases/RSS";
        final SyndFeed feed = new SyndFeedInput().build(new XmlReader(new URL(url)));
        System.out.println(feed.getTitle());

    }

}
```

I'm not able to reproduce the error. Please update Rome if you haven't already done this yet :)

**Comment by mrtz96** [comment]
Hi there!

I think I found the problem. If I pass an XMLReader like you @PatrickGotthard, it works fine. However, in my code I have to pass a Document (org.w3c.dom). With this I run into the same error as @gferry. Is there a solution to this? Anything that can be given to Rome should work i guess. Can you now reproduce the error @PatrickGotthard ?

**Comment by antoniosanct** [comment]
Hi, @mrtz96:

It isn't a ROME problem in fact. Parsing like a W3C Document, you must preserve namespace aware in DocumentBuilderFactory creation

```
import java.net.URL;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;
import org.xml.sax.helpers.DefaultHandler;

import com.rometools.rome.feed.synd.SyndFeed;
import com.rometools.rome.io.SyndFeedInput;

public class TestApplication {

    public static void main(final String[] args) throws Exception {

        final String url = "https://www.enisa.europa.eu/media/press-releases/press-releases/RSS";
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
    	dbf.setNamespaceAware(true);
    	dbf.setFeature("http://xml.org/sax/features/external-general-entities", false);
    	dbf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
    	dbf.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
    	DocumentBuilder db = dbf.newDocumentBuilder();
    	db.setErrorHandler(new DefaultHandler());
    	final Document doc = db.parse(new URL(url).openStream());
        final SyndFeed feed = new SyndFeedInput().build(doc);
        System.out.println(feed.getTitle());

    }

}
```

This conversion is covered in JDOM parser by default (in build(File) and build(Reader)). @PatrickGotthard, a possible suggestion is to change build(Document) modifier to avoid public use, forcing build(File) or build(Reader) methods.

Regards,
Antonio.

**Comment by mrtz96** [comment]
Thanks @antoniosanct! That was new to me and it works!
