### ISSUE TITLE
Date parsed wrong

### ISSUE THREAD

**Issue by dsingh-harp** [rometools/rome#441]
I am on a system having timezone as **UTC**. I am trying to read an rss feed (https://timesofindia.indiatimes.com/rssfeeds/296589292.cms) and print **pubDate** , but currently I am getting the wrong date printed having 2 hours of difference between the timezones. The conversion is happening from **IST to UTC** and the time difference should be 5 hrs and 30 mins.

Here is the code.

import com.rometools.rome.feed.rss.Item;
import com.rometools.rome.feed.synd.SyndEntry;
import com.rometools.rome.feed.synd.SyndFeed;
import com.rometools.rome.io.SyndFeedInput;
import com.rometools.rome.io.XmlReader;
import java.net.URL;
import java.util.Date;

```
public class NewsService {

  public static void main(String[] args) {

    NewsService newsService = new NewsService();
    try {
      newsService.printNews("https://timesofindia.indiatimes.com/rssfeeds/296589292.cms");
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public void printNews(String url) throws Exception {

    // read RSS
    SyndFeedInput in = new SyndFeedInput();
    in.setPreserveWireFeed(true);
    SyndFeed feed = in.build(new XmlReader(new URL(url)));

    for (SyndEntry syndEntry : feed.getEntries()) {
      Object obj = syndEntry.getWireEntry();
      Item item = (Item) obj;

      Date date = ((Item) obj).getPubDate();

      System.out.println(item.getTitle() + " " + date);
    }

  }

}

```
For example:
if rss feed contains the pubDate as **Sat, 28 Mar 2020 13:42:38 IST** , the libary parses it to **Sat Mar 28 11:42:38 GMT 2020** ,  which is wrong.

Also, is there any way to update dateformat of the date?

**Comment by PatrickGotthard** [comment]
Version 1.16.0 is on its way to Maven Central.
It should be available soon.
