### ISSUE TITLE
Alternative to ROME Propono

### ISSUE THREAD

**Issue by antoniosanct** [rometools/rome#442]
(Question)

Migrating ROME to 1.12.3 I've noticed that ROME Propono will be removed in the next major version. I'd like to know what is the best alternative to replace deprecated code with new feature.

Thanks a lot! Regards!

**Comment by PatrickGotthard** [comment]
Hi @antoniosanct,

this project is already not actively maintained and we have focused on the core features long time ago. So we are also unable to maintain an alternative for propono.

Regards,
Patrick
