### ISSUE TITLE
Lockup at: new SyndFeedInput().build(new XmlReader(new URL(url)))

### ISSUE THREAD

**Issue by eGit** [rometools/rome#444]
Just playing around with Rome. Repeatedly getting the feed from https://www.china-gadgets.de/feed

After many hours of doing this it eventually just stops without throwing an exception. No timeout or anything else. It just stops execution (probably in native method).

My code: SyndFeed feed = new SyndFeedInput().build(new XmlReader(new URL("https://www.china-gadgets.de/feed")));

See screenshot for stack details.

![Screenshot from 2020-04-28 01-02-19](https://user-images.githubusercontent.com/842855/80429500-8b5cde00-88ec-11ea-8f5b-318a75a26352.png)

**Comment by PatrickGotthard** [comment]
Hi eGit,

that is not a Rome problem. It looks like you're not having trouble with sockets.
My own feed reader is using Rome and fetches dozens of feeds every 5 minutes - I had no problem for years.

Regards,
Patrick

**Comment by eGit** [comment]
Hi Patrick,

thanks. Do you have any idea what my problem is? Is there a possibility that XmlReader is blocking indefinitely? And if not, why is it blocking?

I switched to the build(Document document) method and provide the Document myself from the URL. Since then I have no problems. No blocking.

I am just curious and I thought you are curious yourself, that's why I filed the issue.

**Comment by PatrickGotthard** [comment]
I don't know where the error comes from. Maybe you have reached the maximum number of sockets of your system. It's also possible that you forgot to close opened resources...
