### ISSUE TITLE
can't parse youtube feed with right content

### ISSUE THREAD

**Issue by litterinchina** [rometools/rome#446]
https://www.youtube.com/feeds/videos.xml?channel_id=UCjOl2AUblVmg2rA_cRgZkFg

cann't not get value of node which prefix with media , and also , http://search.yahoo.com/mrss/ is http 404

**Comment by aqt** [comment]
Support for the Media RSS extension (media namespace) is added through a separate dependency `rome-modules`.

After adding that dependency you can use it this way:
```java
SyndEntry entry = ...
MediaEntryModule media = (MediaEntryModule) entry.getModule(MediaModule.URI);
String videoDescription = media.getMediaGroups()[0].getMetadata().getDescription(); // <media:description>
```
