### ISSUE TITLE
Add support for CDATA

### ISSUE THREAD

**Issue by samba2** [rometools/rome#449]
This is still the same issue as in #280 but since it is closed I reopen it.

**Problem**

I need the following XML output:
````
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>My Feed</title>
    <link>http://foo</link>
    <description>My description</description>
    <item>
      <title>item title</title>
      <link>http://bar</link>
      <description><![CDATA[ <hello>world</hello> ]]></description>
    </item>
  </channel>
</rss>
````
However, I only get ROME to output this:
````
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>My Feed</title>
    <link>http://foo</link>
    <description>My description</description>
    <item>
      <title>item title</title>
      <link>http://bar</link>
      <description>&lt;![CDATA[ &lt;hello&gt;world&lt;/hello&gt; ]]&gt;</description>
    </item>
  </channel>
</rss>
````
Apparently the CDATA section is ignored and the content of "description" is escaped.

**Question**
Is there any constellation how I can get ROME to produce an RSS V2 feed with an unescaped "description" section? Unfortunately I am implementing a given requirement so it has to be the "description" field.

This is my current code:
````
Channel feed = new Channel();
feed.setFeedType("rss_2.0");
feed.setTitle("My Feed");
feed.setDescription("My description");
feed.setLink("http://foo");
feed.setUri("http://feed-address");

Item item = new Item();
item.setTitle("item title");
item.setLink("http://bar");
Description description = new Description();
description.setType("application/xml");
description.setValue("<![CDATA[ <hello>world</hello> ]]>");
item.setDescription(description);

feed.setItems(Arrays.asList(item));

System.out.println(new WireFeedOutput().outputString(feed));
````

Many thanks for your support.

**Comment by PatrickGotthard** [comment]
Hi @samba2,

ROME does currently not support unescaped CDATA sections. The reasons are already explained the given issue #280. We currently have no resources to implement this feature. 

If you don't need other functionalities of ROME other than generating an RSS 2.0 feed, you have the possibility to use any XML library for that purpose at the moment.

I hope this helps.

Regards,
Patrick

**Comment by samba2** [comment]
Hi @PatrickGotthard ,

Thank you for your response. Your hint to simply use an existing XML library was really useful as I was previously caught in my (thinking) box RSS=ROME. I will now go ahead using [Xstream](http://x-stream.github.io/) to model an RSS feed containing those awkward CDATA items.

All the best,

Maik

**Comment by gleb-kosteiko** [comment]
Hi, 
Today I faced with the issue trying to parse such feed https://vanilla-java.github.io/rss/ to SyndFeed object:
```
SyndFeedInput input = new SyndFeedInput();
SyndFeed feed = input.build(new XmlReader(new URL("https://vanilla-java.github.io/rss/")));
```
I got _SAXParseException: An invalid XML character (Unicode: 0x13) was found in the CDATA section_.

As I understand, my case is pretty similar to discussed in that Issue and it's related more to XML parser not to Rome directly, but maybe you could help me to figure out how I could to workaround that? Maybe I could configure Rome to use some another XML parsers or something like this?

And I'd like also to say thank you for you library :)

**Comment by SvenWoltmann** [comment]
I support this feature request. 

We want to extend our RSS feed so that it can be read by https://www.smartnews.com/.

They require us to use CDATA for the HTML content.

**Comment by ptim** [comment]
@SvenWoltmann I came here due to smart news, too; here's my dirty solution:

```java
import org.jdom2.CDATA;

// ...

public void generateAnalytics(final SmartNewsFeedEntryModuleImpl snf, final Element element) {
        if (snf.getGaProperty() != null
                && snf.getGaCookieDomain() != null
                && snf.getPageUrl() != null
        ) {
            String gaScript = "<script>"
                    + "(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){"
                    + "(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),"
                    + "m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)"
                    + "})(window,document,'script','//www.google-analytics.com/analytics.js','ga');"
                    + "ga('create', '%s', '%s');"
                    + "ga('require', 'displayfeatures');"
                    + "ga('set', 'referrer', 'http://www.smartnews.com/');"
                    + "ga('send', 'pageview', '%s');"
                    + "</script>";

            gaScript = String.format(
                    gaScript,
                    snf.getGaProperty(),
                    snf.getGaCookieDomain(),
                    snf.getPageUrl()
            );

            Element snfEl = new Element("analytics", NAMESPACE);
            snfEl.addContent(new CDATA(gaScript));

            element.addContent(snfEl);
        }
    }
```
