### ISSUE TITLE
version 1.14 pom file needs fix the version number

### ISSUE THREAD

**Issue by JessieZhu2000** [rometools/rome#452]
https://repo1.maven.org/maven2/com/rometools/rome/1.14.0/rome-1.14.0.pom

<parent>
<version>${revision}</version>
</parent>

should be updated to 
<version>1.14.0</version>

**Comment by PatrickGotthard** [comment]
Hi @JessieZhu2000,

thanks for your report. I have reverted some changes from our release build.
Version 1.14.1 should be usable again - it will be available soon.

Regards,
Patrick
