### ISSUE TITLE
No documentation (or no support?) for working with a single entry without a feed

### ISSUE THREAD

**Issue by jihu** [rometools/rome#456]
Hi,

I just started to look into using ROME to parse the data of a webservice, and insert new data into it. And the webservice follows the Atom standard. BUT it doesn't use any feed, only the entry object directly. Ie the root object is a:
`<entry xmlns="http://www.w3.org/2005/Atom">`
I am having trouble parsing this data, and outputting the resulting object as a String. And also I am not sure how to create objects of this kind, and output that as a String.

Note, I'm not talking about a feed with a single entry. There is no feed object at all, only the entry object. This is allowed by the standard, and is apparently called "Atom Entry Document".

Since there is no SyndEntryInput or SyndEntryOutput, how is one supposed to do this? Or is this use case simply not supported by ROME? If not, do you have any other java library to suggest?

**Comment by PatrickGotthard** [comment]
Hi @jihu,

this use-case ist not supported. But it should be easy to implement with Standard Java APIs.

Regards,
Patrick
