### ISSUE TITLE
DateParser.parseDate returns null 

### ISSUE THREAD

**Issue by dalevskaya** [rometools/rome#457]
Hi,

I am consuming an Atom feed where dates have the following format: yyyy-MM-dd'T'HH:mm:ss.sZ". 
For example **2020-10-06T14:35:10.492186Z**. 
DateParser.parseDate() returns null. 
Is that a bug?

Best
Alexandra

**Comment by dalevskaya** [comment]
Found how to configure custom DateTime format masks -> http://rometools.github.io/rome/RssAndAtOMUtiliEsROMEV0.7DateAndTimeParsing.html

**Comment by commel** [comment]
Shouldn't this be matched by the Default parser?

* gitlab atom format:
```
<updated>2020-03-23T16:20:55Z</updated>
```
* or this (github release.atom feed)
```
<updated>2021-07-04T17:51:52+02:00</updated>
```
