### ISSUE TITLE
support opds?

### ISSUE THREAD

**Issue by wangsuicheng** [rometools/rome#459]

**Comment by patexoid** [comment]
I use rometool to read and create opds and it's already works fine for me
as I remember you should do nothing to read opds `SyndFeed feed = new SyndFeedInput().build(new XmlReader(connection));` works out of the box (not working with gzip encoding https://github.com/rometools/rome/issues/461)
and for writing you need to create OPDS generator.copy of com.rometools.rome.io.impl.Atom10Generator  with small changes like this [OPDSGenerator](https://github.com/patexoid/ZombieLib2/blob/master/opds/src/main/java/com/patex/zombie/opds/model/OPDSGenerator.java)) (not excelent but it's working). Also you should register it [https://rometools.github.io/rome/RssAndAtOMUtilitiEsROMEV0.5AndAboveTutorialsAndArticles/RssAndAtOMUtilitiEsROMEPluginsMechanism.html](url)
