### ISSUE TITLE
parse "http://main_test.geekpark.net/rss.rss" failed 

### ISSUE THREAD

**Issue by allentown521** [rometools/rome#460]
Caused by: org.jdom2.input.JDOMParseException: Error on line 116: At line 116, column 598: not well-formed (invalid token);

but i try other rss client not use rome is normal

**Comment by allentown521** [comment]
</description>
<source>极客公园</source>
<pubDate>Tue, 24 Nov 2020 08:46:03 +0800</pubDate>
</item>
<item>
    <title>
        <![CDATA[定了！极客公园创新大会一月见]]>

It seems that the problem is that there is a Chinese exclamation mark （！） in the title tag, but can this problem be solved? The inoreader service is normal, indicating that he also handled this situation

**Comment by fschiettecatte** [comment]
I opened this feed in both Chrome and Firefox and both tell me there is an error with the UTF-8 in the feed. I don't think this is a problem with Rome, inoreader may well be silent about UTF-8 issues.

**Comment by allentown521** [comment]
If the problem is identified and there are ways to circumvent it, why not
try to solve it? The compatibility of rome should be getting better, right?

François Schiettecatte <notifications@github.com> 于2020年12月1日周二 上午12:44写道：

**Comment by fschiettecatte** [comment]
You can use [String(byte[] bytes, Charset charset)](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#String-byte:A-java.nio.charset.Charset-) to convert the feed from bytes to a string before passing it to Rome.

**Comment by allentown521** [comment]
hi，i only see SyndFeedInput.build(Reader/File/InputSource/Document),
my code is :
val romeFeed = input.build(XmlReader(response.body()?.byteStream()))
so may i should convert byte to String ,and then to Document, and then pass
to build method?

François Schiettecatte <notifications@github.com> 于2020年12月1日周二 上午9:18写道：

**Comment by fschiettecatte** [comment]
You can wrap the string in a StringReader(), as follows:

```
SyndFeedInput syndFeedInput = new SyndFeedInput();
syndFeed = syndFeedInput.build(new StringReader(feedString))
```
 I don't know how you are getting the url, but you want to read bytes.

**Comment by allentown521** [comment]
hi,seems it is useless:
i change code to
 val romeFeed = input.build(StringReader(String(response.body()?.bytes()!!,
Charset.forName("UTF-8"))))

exception here:
     Caused by: org.jdom2.input.JDOMParseException: Error on line 754: At
line 754, column 598: not well-formed (invalid token)
        at
org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
        at
org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
        at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:233)
        at
com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)

     Caused by: org.apache.harmony.xml.ExpatParser$ParseException: At line
754, column 598: not well-formed (invalid token)
        at
org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:509)
        at
org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:494)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:315)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:273)
        at
org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
        at
org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
        at
com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:233)
        at
com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)



by the way , i download the latest version of chrome(87),It is also
processed and can be displayed normally

François Schiettecatte <notifications@github.com> 于2020年12月1日周二 上午11:20写道：

**Comment by fschiettecatte** [comment]
I just tried this code and it works for me now:

```
import com.rometools.rome.feed.synd.SyndFeed;
import com.rometools.rome.io.SyndFeedInput;
import com.rometools.rome.io.XmlReader;

final URL url = new URL("http://main_test.geekpark.net/rss.rss");
final SyndFeedInput syndFeedInput = new SyndFeedInput();
final SyndFeed syndFeed = syndFeedInput.build(new XmlReader(url));

```

And the feed XML does not report an error in either Chrome or Firefox, so it was correct when I tested it. But it was not correct when I tested it before and what I noticed was the error was being reported in difference parts of the feed when I reloaded it which suggests that the bad content was being dynamically generated.

**Comment by allentown521** [comment]
Indeed, the problematic content has been covered by the new ones and cannot
be tested now. Can you use unit tests to test? After all, the problem is
relatively clear. thanks!

François Schiettecatte <notifications@github.com> 于2020年12月2日周三 上午2:46写道：

**Comment by fschiettecatte** [comment]
Some test cases would be great, and did you try this constructor for XmlReader: 

`public XmlReader(final InputStream is, final boolean lenient) `

so:

`final SyndFeed syndFeed = syndFeedInput.build(new XmlReader(url.openStream(), true));`

**Comment by allentown521** [comment]
i never used it before , always use okhttp instead, Do you think it will
make a difference？

François Schiettecatte <notifications@github.com> 于2020年12月2日周三 上午10:09写道：

**Comment by fschiettecatte** [comment]
I wasnt talking about a test case, I was wondering if you had tried the 'lenient' flag for XmlReader(), actually I don't know what your original code looked like.

**Comment by allentown521** [comment]
i use XmlReader(final InputStream is), the lenient is true by default ；
code here:
fun parseFeedResponse(feedUrl: String): SyndFeed {
        try {
            createCall(feedUrl).execute().use { response ->
                val input = SyndFeedInput()
                return input.build(XmlReader(response.body()?.byteStream()))
            }
        } catch (t: Throwable) {
            throw t
        }
    }

François Schiettecatte <notifications@github.com> 于2020年12月2日周三 下午11:19写道：

**Comment by fschiettecatte** [comment]
Ok, well problem is that since the bad content has rolled off the feed (I just checked again), and I did not keep a version, I cant really dig anymore into this. However happy to help if the bad content reappears. I would suggest you close this issue.
