### ISSUE TITLE
How to use custom tags?

### ISSUE THREAD

**Issue by hyeokdev** [rometools/rome#467]
Hello, I am a user who is using rom well.
I want to bring custom tags.
I tried it but failed.
![캡처](https://user-images.githubusercontent.com/55627705/107188256-b4d59900-6a2a-11eb-92de-0aef41b6daa3.PNG)

how to use custom tags?

my environment : jdk11, rome 1.15.0, spring-boot 2.4.0

**Comment by neroux** [comment]
>  I tried it but failed.

What did you try?

**Comment by PatrickGotthard** [comment]
I think you habe to write a module for that but I'm not sure whether this works without an additional namespace.
