### ISSUE TITLE
Empty item categories not skipped

### ISSUE THREAD

**Issue by neroux** [rometools/rome#472]
Not sure if this is an issue per se, but Rome currently imports completely empty categories as well

```xml
<category />
```

[RSS 0.92](http://backend.userland.com/rss092#ltcategorygtSubelementOfLtitemgt) does not exactly specify the behaviour in that case, but it would appear as if a name was supposed to be there.

Gamespot would be an example for such a feed - https://www.gamespot.com/feeds/news/

The code in question is

https://github.com/rometools/rome/blob/c36bfd8f4745d25d4435b7e876d3d533df1b79ce/rome/src/main/java/com/rometools/rome/io/impl/RSS092Parser.java#L157-L183

**Comment by PatrickGotthard** [comment]
This enhancement will be available in Rome 1.18.0
