### ISSUE TITLE
Adding namespace to RSS element

### ISSUE THREAD

**Issue by abhishekagg19** [rometools/rome#519]
I am unable to find way to add namespace at the RSS element level:

<rss version="2.0"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:atom="http://www.w3.org/2005/Atom"
  >

**Comment by PatrickGotthard** [comment]
Hi @yaroslavm,

in fact Rome is for creating feeds. @abhishekagg19 you have to build a plugin to add a namespace. Please have a look at the rome-modules directory.

Regards,
Patrick

**Comment by yaroslavm** [comment]
@PatrickGotthard hah😅 didn't know that.
