### ISSUE TITLE
Rome | RSS Feed | CDATA encoding: Exceptionjava.lang.ClassCastException

### ISSUE THREAD

**Issue by jeevan-eranti** [rometools/rome#524]
We are trying to include HTML code in the RSS description or content-encoded fields using CDATA.

**CDATA section (CDATA encoding): Sample code**

final List<String> contents = new ArrayList<>();
contents.add("<p>HTML content is here!</p>");
final ContentModule module = new ContentModuleImpl();
module.setEncodeds(contents);
entry.getModules().add(module);

**Exception:** 
java.lang.ClassCastException: class com.rometools.modules.content.ContentModuleImpl cannot be cast to class com.rometools.rome.feed.module.Module (com.rometools.modules.content.ContentModuleImpl is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @3960488b; com.rometools.rome.feed.module.Module is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @23366977)

Rome (com.rometools.rome)  --> 1.18.0
Rome Modules (com.rometools.rome-modules) ---> 1.18.0
jdom2 --> 2.0.6.1

Any suggestions on how to resolve this issue?

**Comment by antoniosanct** [comment]
Hi! Could you put the entire implementation??

Using this test case in ROME works fine! (recover from ContentModuleImplTest, extending with AbstractTestCase)

`final SyndFeedInput input = new SyndFeedInput();`
`final SyndFeed feed = input.build(new XmlReader(new File(getTestFile("xml/test-rdf.xml")).toURI().toURL()));`
`final SyndEntry entry = feed.getEntries().get(0);`
`final List<String> contents = new ArrayList<>();`
`contents.add("<h1>Welcome to Modules from the ROME Framework!!</h1>");`
`final ContentModule test = new ContentModuleImpl();`
`test.copyFrom(module);`
`test.setEncodeds(contents);`
`entry.getModules().add(module);`

**Comment by PatrickGotthard** [comment]
I close this issue due to inactivity.
