### ISSUE TITLE
Image Url returns Pictures in Low Quality

### ISSUE THREAD

**Issue by lukonjun** [rometools/rome#546]
Hi there, this is only indirectly related to the library, however, I thought I still ask for your advice.   
I am using Rome to fetch numerous RSS Feeds, save article Information in a Database, and then expose this Information via a REST API which is consumed by a mobile application.  
The Problem I am currently Facing is that the `img_url` of Articles provide sometimes Pictures of low quality and I don't know how to overcome this. Especially the magazine Bild gives me a headache that returns pictures in low quality if you don't specify a resolution in the URL query parameters, but also other RSS Feeds provide sometimes pictures in low quality. 
<img width="412" alt="Bildschirmfoto 2022-04-23 um 08 39 04" src="https://user-images.githubusercontent.com/64301331/164883442-ecd1c569-6b39-408d-a94e-d0ccc43a653b.png">
Have you experienced similar issues and/or do you have any ideas, recommendation how to solve this?
Thanks a lot in advance!

**Comment by antoniosanct** [comment]
Hi, @lukonjun!

I got an Bild.de RSS sample ([link](https://www.bild.de/rssfeeds/vw-alles/vw-alles-26970192,dzbildplus=false,sort=1,teaserbildmobil=false,view=rss2,wtmc=ob.feed.bild.xml)). In this case, RSS092Parser get the 'description' node at each item, that contains an thumbnail image.

Reviewing the feed, you could parse it with the Yahoo! MediaRSS module plugin included in rome-modules project. Try to include the MediaModuleParser in a custom rome.properties to parse the original image at the item:

```
rss_2.0.item.ModuleParser.classes=com.rometools.modules.mediarss.io.MediaModuleParser
```

With this approach, the SyndFeed contains a MediaEntryModule reference that contains the image as you need:
```
for (SyndEntry syndEntry : feed.getEntries()) {
  MediaEntryModule mm = (MediaEntryModule) syndEntry.getModule(MediaModule.URI);
  LOG.info("{}", mm.getMediaContents()[0].getReference());
}
```

Regards!

**Comment by lukonjun** [comment]
Hi @antoniosanct, thanks a lot for your answer!

For some reason, I am not able to import the MediaEntryModule Class. I checked my pom.xml
```
<dependency>
	<groupId>com.rometools</groupId>
	<artifactId>rome</artifactId>
	<version>1.18.0</version>
</dependency>
```
And also verified the included jars
<img width="621" alt="Bildschirmfoto 2022-04-30 um 09 26 15" src="https://user-images.githubusercontent.com/64301331/166096496-0837f607-1a20-4f8a-8ee4-b0faff62f923.png">
Might be missing a silly point but could you maybe share your pom.xml, this import is not working for me `import com.rometools.modules.mediarss.MediaEntryModule;`

**Comment by PatrickGotthard** [comment]
@lukonjun You have to add the rome-modules dependency to use the MediaRSS module :)
