### ISSUE TITLE
OPML Generator Creates "weird" `<docs>` element by default.

### ISSUE THREAD

**Issue by kevincox** [rometools/rome#551]
Hi, I'm investigating a weird feed which was generated by https://github.com/39aldo39/Flym-DecSync which appears to use rome-opml.

From a quick reading of the code it seems that the `Opml.docs` field is [`null` by default](https://github.com/rometools/rome/blob/8f9a896f2ebfae3886ac0eaaaabf50bb0e7e9595/rome-opml/src/main/java/com/rometools/opml/feed/opml/Opml.java#L42). This is then used to generate the OPML which appears to result in a tag of `<docs />`.

https://github.com/rometools/rome/blob/8f9a896f2ebfae3886ac0eaaaabf50bb0e7e9595/rome-opml/src/main/java/com/rometools/opml/io/impl/OPML20Generator.java#L71-L72

`<docs>` is not a required tag in the OPML spec but it is quite weird to have it present as an empty element rather than having a URL or not existing at all. I think it would be best if this could be fixed. I think the ideal solution is probably to do both.

1. Make the `docs` field default to http://opml.org/spec2.opml so that by default all feeds are generated with a reasonable doc link.
2. Skip emitting the `<docs>` element at all if the `docs` field is null.

**Comment by PatrickGotthard** [comment]
This will be released with version 2.0.0. See https://github.com/rometools/rome/commit/dd8ab5867c0a4cbf46b381e80a000e61a538dccc
