### ISSUE TITLE
Customized title for RSS

### ISSUE THREAD

**Issue by virendra2609** [rometools/rome#557]
Customized title for RSS where html tags are coming in the RSS feed but with current version the library sets the title to an empty string.

**Comment by antoniosanct** [comment]
Hi, @virendra2609:

Could you give us a sample? README explains how to generate a RSS 2.0 feed, customizing the feed title.

Regards!

**Comment by virendra2609** [comment]
Hey,

Sorry to update a bit late. Pasted the file for your reference. Did not find anything related to this in the Readme.

`<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/scripts/rss.xsl" ?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
    <channel>
        <title>Test</title>
        <description/>
        <link>https://www.gao.gov/rss/press.xml</link>
        <lastBuildDate>Mon, 30 May 2022 08:24:07 -0400</lastBuildDate>
        <generator>GAO</generator>
        <image>
            <url>https://www.gao.gov/themes/custom/gao/img/gao-logo-rss.gif</url>
            <title>Press Release</title>
            <link>https://www.gao.gov/rss/press.xml</link>
            <description>Feed provided by GAO.</description> 
        </image>

            <item>
                **<title>**<a href="/press-release/gao-makes-medpac-appointments-6" hreflang="en">GAO Makes MedPAC Appointments</a>**</title>**
                <link>https://www.gao.gov/press-release/gao-makes-medpac-appointments-6</link>
                <description>WASHINGTON, DC (May 26, 2022) – Gene L. Dodaro, Comptroller General of the United States and head of the U.S. Government Accountability Office (GAO), today announced the appointment of five new members to the Medicare Payment Advisory Commission (…</description>
                <pubDate>Wed, 25 May 2022 10:17:57 -0400</pubDate>
                <guid isPermaLink="false">/press-release/gao-makes-medpac-appointments-6</guid>
            </item>
            <item>
                **<title>**<a href="/press-release/annual-report-government-fragmentation-overlap-and-duplication-flags-billions-dollars-potential-savings" hreflang="en">Annual Report on Government Fragmentation, Overlap, and Duplication Flags Billions of Dollars in Potential Savings</a>**</title>**
                <link>https://www.gao.gov/press-release/annual-report-government-fragmentation-overlap-and-duplication-flags-billions-dollars-potential-savings</link>
                <description>Washington, D.C. (May 11, 2022) – The U.S. Government Accountability Office (GAO) today issued its 12th annual report identifying opportunities to reduce fragmentation, overlap, and duplication across the federal government and potentially save…</description>
                <pubDate>Thu, 05 May 2022 10:11:02 -0400</pubDate>
                <guid isPermaLink="false">/press-release/annual-report-government-fragmentation-overlap-and-duplication-flags-billions-dollars-potential-savings</guid>
            </item>
    </channel>
</rss>
`

**Comment by virendra2609** [comment]
Hey @antoniosanct,

Any further updates on this ?

**Comment by antoniosanct** [comment]
Hi, @virendra2609:

Pasted-code is not XML well-formed. Please, give us a better sample to generate a RSS 2.0 test case.

Regards,
Antonio.

**Comment by virendra2609** [comment]
Hi @antoniosanct,

Below i have pasted the xml

`<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/scripts/rss.xsl" ?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
    <channel>
        <title>Press Release</title>
        <description/>
        <link>https://www.gao.gov/rss/press.xml</link>
        <lastBuildDate>Thu, 18 Aug 2022 02:54:33 -0400</lastBuildDate>
        <generator>GAO</generator>
        <image>
            <url>https://www.gao.gov/themes/custom/gao/img/gao-logo-rss.gif</url>
            <title>Press Release</title>
            <link>https://www.gao.gov/rss/press.xml</link>
            <description>Feed provided by GAO.</description> 
        </image>
            <item>
                <title><a href="/press-release/annual-report-government-fragmentation-overlap-and-duplication-flags-billions-dollars-potential-savings" hreflang="en">Annual Report on Government Fragmentation, Overlap, and Duplication Flags Billions of Dollars in Potential Savings</a></title>
                <link>https://www.gao.gov/press-release/annual-report-government-fragmentation-overlap-and-duplication-flags-billions-dollars-potential-savings</link>
                <description>Washington, D.C. (May 11, 2022) – The U.S. Government Accountability Office (GAO) today issued its 12th annual report identifying opportunities to reduce fragmentation, overlap, and duplication across the federal government and potentially save…</description>
                <pubDate>Thu, 05 May 2022 10:11:02 -0400</pubDate>
                <guid isPermaLink="false">/press-release/annual-report-government-fragmentation-overlap-and-duplication-flags-billions-dollars-potential-savings</guid>
            </item>
            <item>
                <title><a href="/press-release/new-fiscal-health-report-urges-long-term-strategy-help-address-nations-growing-fiscal-challenges" hreflang="en">New “Fiscal Health” Report Urges Long-Term Strategy to Help Address the Nation’s Growing Fiscal Challenges</a></title>
                <link>https://www.gao.gov/press-release/new-fiscal-health-report-urges-long-term-strategy-help-address-nations-growing-fiscal-challenges</link>
                <description>Washington, D.C. (May 05, 2022)—With the federal government now facing rising interest rates on its mounting debt, the U.S. Government Accountability Office today issued its sixth annual report on the nation’s fiscal health. The report again warns…</description>
                <pubDate>Thu, 28 Apr 2022 09:50:57 -0400</pubDate>
                <guid isPermaLink="false">/press-release/new-fiscal-health-report-urges-long-term-strategy-help-address-nations-growing-fiscal-challenges</guid>
            </item>
            <item>
                <title><a href="/press-release/gao-makes-macpac-appointments-and-reappointments" hreflang="en">GAO Makes MACPAC Appointments and Reappointments</a></title>
                <link>https://www.gao.gov/press-release/gao-makes-macpac-appointments-and-reappointments</link>
                <description>WASHINGTON, D.C. (May 2, 2022)—Gene L. Dodaro, Comptroller General of the United States and head of the U.S. Government Accountability Office (GAO), today announced the appointment of four new members to the Medicaid and CHIP Payment and Access…</description>
                <pubDate>Wed, 27 Apr 2022 13:24:20 -0400</pubDate>
                <guid isPermaLink="false">/press-release/gao-makes-macpac-appointments-and-reappointments</guid>
            </item>
            <item>
                <title><a href="/press-release/gaos-latest-covid-relief-report-makes-15-new-recommendations-improper-payments-public-health-data-collection-and-critical-manufacturing" hreflang="en">GAO’s Latest COVID Relief Report Makes 15 New Recommendations on Improper Payments, Public Health Data Collection, and Critical Manufacturing</a></title>
                <link>https://www.gao.gov/press-release/gaos-latest-covid-relief-report-makes-15-new-recommendations-improper-payments-public-health-data-collection-and-critical-manufacturing</link>
                <description>WASHINGTON, DC (April 27, 2022)— As the country enters its third year of the coronavirus pandemic, the U.S. Government Accountability Office (GAO) is making new recommendations to reduce improper payments in COVID-19 programs and improve public…</description>
                <pubDate>Mon, 25 Apr 2022 12:11:48 -0400</pubDate>
                <guid isPermaLink="false">/press-release/gaos-latest-covid-relief-report-makes-15-new-recommendations-improper-payments-public-health-data-collection-and-critical-manufacturing</guid>
            </item>
            <item>
                <title><a href="/press-release/gao-seeks-members-new-tribal-advisory-council" hreflang="en">GAO Seeks Members for New Tribal Advisory Council</a></title>
                <link>https://www.gao.gov/press-release/gao-seeks-members-new-tribal-advisory-council</link>
                <description>WASHINGTON, D.C. (April 7, 2022)--The U.S. Government Accountability Office (GAO) today announced plans to form its first-ever Tribal Advisory Council (TAC) to provide insights and recommendations on issues affecting Tribal Nations and their…</description>
                <pubDate>Thu, 31 Mar 2022 09:53:29 -0400</pubDate>
                <guid isPermaLink="false">/press-release/gao-seeks-members-new-tribal-advisory-council</guid>
            </item>
            <item>
                <title><a href="/press-release/gao-urges-action-10-ways-improve-oversight-emergency-relief-funds-and-future-federal-spending" hreflang="en">GAO Urges Action: 10 Ways to Improve Oversight of Emergency Relief Funds And Future Federal Spending</a></title>
                <link>https://www.gao.gov/press-release/gao-urges-action-10-ways-improve-oversight-emergency-relief-funds-and-future-federal-spending</link>
                <description>WASHINGTON, D.C. (March 17, 2022)—In testimony today before the Senate Homeland Security and Governmental Affairs Committee, Gene L. Dodaro, Comptroller General of the United States and head of the U.S. Government Accountability Office (GAO),…</description>
                <pubDate>Wed, 16 Mar 2022 10:48:55 -0400</pubDate>
                <guid isPermaLink="false">/press-release/gao-urges-action-10-ways-improve-oversight-emergency-relief-funds-and-future-federal-spending</guid>
            </item>
            <item>
                <title><a href="/press-release/preparing-biological-incidents%2C-global-and-domestic-threats%2C-science-and-tech-innovation-economy%2C-gao-focuses-dozen-trends-shaping-government" hreflang="en">From Preparing for Biological Incidents, to Global and Domestic Threats, to Science and Tech in an Innovation Economy, GAO Focuses on a Dozen Trends Shaping Government</a></title>
                <link>https://www.gao.gov/press-release/preparing-biological-incidents%2C-global-and-domestic-threats%2C-science-and-tech-innovation-economy%2C-gao-focuses-dozen-trends-shaping-government</link>
                <description>WASHINGTON, D.C. (March 15, 2022)—The U.S. Government Accountability Office (GAO) today issued a dozen trend papers outlining critical challenges facing our nation, all part of the non-partisan, fact-based agency’s new Strategic Plan for Serving the…</description>
                <pubDate>Fri, 11 Mar 2022 09:12:36 -0500</pubDate>
                <guid isPermaLink="false">/press-release/preparing-biological-incidents%2C-global-and-domestic-threats%2C-science-and-tech-innovation-economy%2C-gao-focuses-dozen-trends-shaping-government</guid>
            </item>
            <item>
                <title><a href="/press-release/latest-gao-covid-relief-report-makes-five-new-recommendations-nutrition-assistance%2C-emergency-rental-assistance%2C-and-tax-relief-businesses" hreflang="en">Latest GAO COVID Relief Report Makes Five New Recommendations on Nutrition Assistance, Emergency Rental Assistance, and Tax Relief for Businesses </a></title>
                <link>https://www.gao.gov/press-release/latest-gao-covid-relief-report-makes-five-new-recommendations-nutrition-assistance%2C-emergency-rental-assistance%2C-and-tax-relief-businesses</link>
                <description>WASHINGTON, D.C. (January 27, 2022) – With the Omicron variant presenting new challenges across the country, the Government Accountability Office (GAO) today issued its ninth comprehensive report on COVID relief under the CARES Act, making five new…</description>
                <pubDate>Mon, 24 Jan 2022 11:52:44 -0500</pubDate>
                <guid isPermaLink="false">/press-release/latest-gao-covid-relief-report-makes-five-new-recommendations-nutrition-assistance%2C-emergency-rental-assistance%2C-and-tax-relief-businesses</guid>
            </item>
            <item>
                <title><a href="/press-release/gao-makes-appointments-health-information-technology-advisory-committee-0" hreflang="en">GAO Makes Appointments to the Health Information Technology Advisory Committee</a></title>
                <link>https://www.gao.gov/press-release/gao-makes-appointments-health-information-technology-advisory-committee-0</link>
                <description>WASHINGTON, DC (December 20, 2021) – Gene L. Dodaro, Comptroller General of the United States and head of the U.S. Government Accountability Office (GAO), today announced the appointment of seven members to the Health Information Technology Advisory…</description>
                <pubDate>Thu, 16 Dec 2021 11:05:17 -0500</pubDate>
                <guid isPermaLink="false">/press-release/gao-makes-appointments-health-information-technology-advisory-committee-0</guid>
            </item>
            <item>
                <title><a href="/press-release/gaos-work-led-66.2-billion-financial-benefits-congress-and-american-people" hreflang="en">GAO’s Work Led to $66.2 Billion in Financial Benefits for Congress and the American People </a></title>
                <link>https://www.gao.gov/press-release/gaos-work-led-66.2-billion-financial-benefits-congress-and-american-people</link>
                <description>WASHINGTON, D.C. (November 15, 2021) – The U.S. Government Accountability Office’s (GAO) work generated $66.2 billion in financial benefits for Congress and the American people in fiscal year 2021.  This continues to demonstrate a strong return on…</description>
                <pubDate>Mon, 08 Nov 2021 07:26:55 -0500</pubDate>
                <guid isPermaLink="false">/press-release/gaos-work-led-66.2-billion-financial-benefits-congress-and-american-people</guid>
            </item>
            <item>
                <title><a href="/press-release/statement-microsoft-bid-protest-decision" hreflang="en">Statement on Microsoft Bid Protest Decision</a></title>
                <link>https://www.gao.gov/press-release/statement-microsoft-bid-protest-decision</link>
                <description>The following is a statement from Ralph O. White, Managing Associate General Counsel for the Procurement Law Division at GAO regarding today’s decision resolving the bid protest filed by the Microsoft Corporation, B-420004, B-420004.2.

On October…</description>
                <pubDate>Thu, 28 Oct 2021 14:16:00 -0400</pubDate>
                <guid isPermaLink="false">/press-release/statement-microsoft-bid-protest-decision</guid>
            </item>

    </channel>
</rss>`

**Comment by virendra2609** [comment]
Hi @antoniosanct,

Please find the attached xml.

[test-title.zip](https://github.com/rometools/rome/files/9372724/test-title.zip)

**Comment by antoniosanct** [comment]
Hi, @virendra2609:

ROME actually not supports nested HTML into item title because of JDOM expects a text node. In fact, RSS 2.0 specification indicates that title item always sets a non-HTML text. The correct use of this approach is using link item.

On the other hand, a possible solution is a CDATA nested the entire title item, like this:

```
<title><![CDATA[<html content>]]></title>
```

Regards,
Antonio.

**Comment by PatrickGotthard** [comment]
Feel free to reopen the issue when it's still relevant :)
