### ISSUE TITLE
Is there a timeout setting function？

### ISSUE THREAD

**Issue by zdx0122** [rometools/rome#588]
Is there a timeout setting function？

rome use URLConnection as its httpclient, but i don't found setConnectTimeout() , it cause code not work and thread keeps waiting

so,  can this function be added

thanks

**Comment by antoniosanct** [comment]
Hi, @zdx0122 :
1) Please, add a use case about your request. We'd need more information to help you.
2) There's a XmlReader public constructor where you can specify an URLConnection and set the connect timeout:
```
final URLConnection conn = url.openConnection();
conn.setConnectTimeout(1800);
try (final XmlReader xmlReader = new XmlReader(conn)) {

} catch (Exception e) {
    e.printStackTrace();
}
```
Is this what you are looking for?
Regards,
Antonio.

**Comment by zdx0122** [comment]
thanks，Your answer solves my problem

**Comment by PatrickGotthard** [comment]
@zdx0122 I will suggest you to fetch the feed with another library and just use Rome for parsing.
