### ISSUE TITLE
Support `satisfies` keyword (since TypeScript 4.9)

### ISSUE THREAD

**Issue by Newbie012** [rometools/rome#591]
Given the following code:

```ts
const X = 5 satisfies number;
```

Getting:

> Expected a semicolon or an implicit semicolon after a statement, but found none

Expected:

```ts
const X = 5 satisfies number;
```

[See playground](https://docs.rome.tools/playground/?lineWidth=100&indentStyle=space&trailingComma=none&indentWidth=4&code=YwBvAG4AcwB0ACAAWAAgAD0AIAA1ACAAcwBhAHQAaQBzAGYAaQBlAHMAIABuAHUAbQBiAGUAcgA7AA%3D%3D)

**Comment by PatrickGotthard** [comment]
Hi @Newbie012,

this project has nothing to do with your issue.

Regards,
Patrick

**Comment by Newbie012** [comment]
I'm so sorry. I got confused with https://github.com/rome/tools 🤦
