### ISSUE TITLE
Dependency versions update

### ISSUE THREAD

**Issue by juzi** [rometools/rome#608]
Hi, 
my project relies on rome to read atom feeds. However, my dependency checker gives me a code red because of vulnerabilities in Version 1.18.0. Could you please at least merge the pull requests that your dependabot created for you and build a new version? Maybe like that the vulnerabilities will be resolved.

**Comment by PatrickGotthard** [comment]
Hi @juzi, 

I've published a statement about the future of the project here: https://github.com/rometools/rome/issues/610

I will release an updated version soon.

Regards,
Patrick
