### ISSUE TITLE
The future of the project

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#610]
Hello everyone,

it's time to talk about the future of the project. Unfortunately, I don't have time to actively develop the project further. That's why there have been no changes for quite a while now.

I decided to reset the main branch to the latest release version. This gives me the opportunity to at least keep the used libraries up to date. I apologize in advance if I broke some forks with this change. The previous development state is now on the **development** branch.

I would like to give the project into other hands, but I have no experience how to do that properly:
- who should get admin permissions for the project?
- who should be able to release new versions (including access data and GPG keys for Maven Central)?
- who should be able to decide about further development?

If you have answers to the questions or experience with such changes, feel free to leave me a comment below.

Regards,
Patrick

**Comment by antoniosanct** [comment]
Hi, @PatrickGotthard

First of all, I appreciate your hard work on this project and I would like you to continue collaborating on it. By me, I would like to continue collaborating at this project too, but I think that I may not be the best person to manage it.

I am still convinced to carry out other tasks like Java DOM migration. In fact, I still maintain the branch and it would be a good idea to integrate it in version 3.0.0. However, I would prefer to get feedback from the rest of the people who have historically been involved in the project.

Regards,
Antonio

**Comment by neroux** [comment]
I am not sure anybody here - apart from you - could tell who should get administrative permissions, respectively manage the project. I remember there were a few people you originally mentioned, but they do not seem to have been active any more either.

I have made a few smaller contributions, mostly fixes, but as I am using the library in one of my own projects, I'd certainly like to continue collaborating as well.

As for the DOM migration, @antoniosanct mentioned, I remember there were certain issues mentioned in the context of Android. If Android does nto support that yet, that may be a showstopper of course.

**Comment by PatrickGotthard** [comment]
Hi @all,

I'm happy to announce that Rome 2.0.0 is now available, that contains all relevant changes from the "old" development branch.

According to the number of issues and PRs I think that I'll be able to maintain the project further - so I'll close this discussion :)

Regards,
Patrick
