### ISSUE TITLE
does anyone have experience to use rome with huge RSS files

### ISSUE THREAD

**Issue by zhiqiangZHAO** [rometools/rome#629]
Hi friends,

First I want to thank you for making this great library.

We are using it to ingest some data in XML format. And sometimes we need to handle file as big as 1GB.
We are using machine with big memory, like 14GB MEM. It works, but not scalable.
It would be great if we could lower the memory usage.

Does anyone have any experience for that?
Any help is appreciate!

What we do is quite simple: read RSS, convert it to an internal format, write to DB.
We use kotlin.

We parse the local RSS file at first.
`val syndFeed = SyndFeedInput().build(reader)`
Then we use the following code
```
syndFeed.entries
                    .stream()
                    .map(function1)
                    .map(function2)
                    .forEach { --processing-- }
```

**Comment by antoniosanct** [comment]
Hi, @zhiqiangZHAO :

Rome has like main feature to take JDOM implementation, then it is obviously that it needs a lot of heap memory to execute using large RSS files.

A simple class to make a stress test took these results (My environment: Rocky Linux, i7-8550U CPU @ 1.80GHz, 16GB SODIMM DDR4, OpenJDK 11.0.18)

RSS 2.0 feed with 100,000 entries - 93.800 MB
Time elapsed (Generator): 10.646 sec.
Time elapsed (Parse): 35.287 sec.
RSS 2.0 feed with 200,000 entries - 188.976 MB
Time elapsed (Generator): 15.696 sec.
Time elapsed (Parse): 56.152 sec.

Adding more entries causes out of memory with <= 4GB heap memory. If you need more entries or bigger file size, then you can increase heap size and share your results.

Regards,
Antonio.

**Comment by zhiqiangZHAO** [comment]
thank you Antonio!

I noticed I could use SAX as input.
https://github.com/rometools/rome/blob/dc1461d7f1a657758785326cb576554292fa5384/rome/src/main/java/com/rometools/rome/io/SyndFeedInput.java#L164

Will it use less memory than the default one?

**Comment by PatrickGotthard** [comment]
Hi @zhiqiangZHAO,

I really don't know whether it makes a difference, internally JDOM will still be used for parsing.
Just try it out and let us know the results :)

Regards,
Patrick

**Comment by zhiqiangZHAO** [comment]
I see. Thanks!
I have an idea: maybe I could split the huge xml file into small chunks, then process them 1 by 1 with rome.
I think I can write a simple parser to split the file. But if there is an existing one that could be better.
Do you know anything could split huge xml file?

**Comment by PatrickGotthard** [comment]
I'll close this issue. Feel free to reopen it if you have further questions :)
