### ISSUE TITLE
Formatter: Add option to ignore end of line format

### ISSUE THREAD

**Issue by dev-ardi** [rometools/rome#659]
I've added rome ci to my pipeline. My git config auto adds crlf automatically when pushing, and rome doesn't like it. I haven't seen an option to disable this behaviour in rome.

**Comment by antoniosanct** [comment]
Hi, @dev-ardi 

Would you put a sample here? which feed type is generated?

Regards,
Antonio.

**Comment by dev-ardi** [comment]
I mistook this repository with https://github.com/rome/tools !!! Sorry

**Comment by dev-ardi** [comment]
I wonder - does this happen often? 😄
